// AI_GENERATED: GENERATED BY CLAUDE CODE
package embed

import "core:fmt"
import "core:io"
import "core:os"
import "core:strings"
import bc "../backend/bytecode"
import bcvm "../backend/bytecode/vm"
import "../parser"
import nr "../tree-walkers/nameresolution"
import tc "../tree-walkers/typechecker"

// NativeFn is a host-language function callable from Myr code.
NativeFn :: bc.NativeFn

// CompileError represents a parse, name-resolution, type, or codegen error.
CompileError :: struct {
	message: string,
	offset:  u32,  // byte offset in source
}

// MyrState is the embedding context: registered natives + compiled module.
// Create with myr_new, free with myr_free.
MyrState :: struct {
	natives:  [dynamic]NativeFn,
	names:    [dynamic]string,   // parallel to natives; names[i] is the Myr name for natives[i]
	module:   ^bc.Module,
	// source bytes for imported modules; kept alive so token .data string slices remain valid.
	_sources: [dynamic][]byte,
}

myr_new :: proc() -> MyrState {
	return MyrState{
		natives  = make([dynamic]NativeFn),
		names    = make([dynamic]string),
		_sources = make([dynamic][]byte),
	}
}

myr_free :: proc(s: ^MyrState) {
	delete(s.natives)
	delete(s.names)
	for src in s._sources { delete(src) }
	delete(s._sources)
	if s.module != nil {
		bc.module_free(s.module)
		s.module = nil
	}
}

// myr_register binds a host function to a Myr name.
// Returns the slot index (for informational use) or -1 if the table is full.
myr_register :: proc(s: ^MyrState, name: string, fn: NativeFn) -> int {
	if len(s.natives) >= 256 do return -1
	slot := len(s.natives)
	append(&s.natives, fn)
	append(&s.names, name)
	return slot
}

// myr_compile parses, type-checks, and bytecode-compiles source.
// source_dir is the directory containing the source file; used to resolve imports
// and to load the entry file's sibling .myr files (a directory is one module).
// source_file is the entry file's basename; its siblings join the main module.
// Returns nil on success; a non-empty slice of errors otherwise.
// The caller owns the returned error slice (delete when done).
myr_compile :: proc(s: ^MyrState, source: string, source_dir: string = "", source_file: string = "") -> []CompileError {
	p   := parser.new_parser(source)
	ast := parser.parse_program(&p)
	defer parser.ast_destroy(&ast)

	if len(p.errors) > 0 {
		errs := make([]CompileError, len(p.errors))
		for e, i in p.errors { errs[i] = {message = strings.clone(parser.decode_parser_error_message(&p.errors[i], source)), offset = e.span.start} }
		delete(p.errors)
		return errs
	}
	delete(p.errors)

	// Build the module table. The entry file is module 0 (main); its nodes are left
	// untagged (module_of falls back to MAIN_MODULE).
	table := parser.module_table_init()
	defer parser.module_table_destroy(&table)

	if source_dir != "" {
		// A directory is one module: the entry file's siblings join the main module.
		if source_file != "" {
			sib_errs := _load_entry_siblings(&ast, &s._sources, source_dir, source_file)
			if sib_errs != nil { return sib_errs }
		}

		// Collect imports from the whole main module (entry + siblings) before loading.
		entry_imports := _collect_imports(&ast, context.temp_allocator)
		stack := make([dynamic]string, context.temp_allocator)
		for imp in entry_imports {
			load_errs := _load_module(&ast, &table, &s._sources, source_dir, imp, parser.MAIN_MODULE, &stack)
			if load_errs != nil { return load_errs }
		}
	}

	nrr := nr.resolve_program(&ast, &table)
	defer nr.nr_result_destroy(&nrr)
	if nrr.error_count > 0 {
		errs := make([]CompileError, int(nrr.error_count))
		for i in 0..<int(nrr.error_count) {
			e := nrr.errors[i]
			errs[i] = {message = strings.clone(e.message), offset = e.span.start}
		}
		return errs
	}

	tcr := tc.typecheck(&ast, &nrr, &table)
	defer tc.tc_result_destroy(&tcr)
	if tcr.error_count > 0 {
		errs := make([]CompileError, int(tcr.error_count))
		for i in 0..<int(tcr.error_count) {
			e := tcr.errors[i]
			msg: string
			if e.message != "" {
				msg = strings.clone(e.message)
			} else {
				exp := tc.type_id_name(e.expected, tcr.type_table[:])
				got := tc.type_id_name(e.found,    tcr.type_table[:])
				msg = fmt.aprintf("type mismatch: expected '%s', got '%s'", exp, got)
			}
			errs[i] = {message = msg, offset = e.span.start}
		}
		return errs
	}

	// comp_errors slices into a stack-allocated array inside compile(); never delete it.
	module, comp_errors := bc.compile(&ast, tcr.types, tcr.type_table[:], s.names[:], &table)
	if len(comp_errors) > 0 {
		errs := make([]CompileError, len(comp_errors))
		for e, i in comp_errors { errs[i] = {message = strings.clone(e.message), offset = e.span.start} }
		return errs
	}

	bc.peephole_optimize(module)

	if s.module != nil { bc.module_free(s.module) }
	s.module = module
	return nil
}

// myr_run executes the compiled module on a fresh VM.
// Panics (returns error) if myr_compile has not been called successfully.
myr_run :: proc(s: ^MyrState) -> Maybe(bcvm.VMError) {
	if s.module == nil do return nil
	machine := bcvm.new_vm()
	machine.natives = s.natives[:]
	defer bcvm.destroy_vm(&machine)
	return bcvm.vm_interpret(&machine, s.module)
}

// myr_run_with_stdin runs the compiled module, routing stdin reads through r.
myr_run_with_stdin :: proc(s: ^MyrState, stdin: io.Reader) -> Maybe(bcvm.VMError) {
	if s.module == nil do return nil
	machine := bcvm.new_vm()
	machine.natives = s.natives[:]
	machine.stdin   = stdin
	defer bcvm.destroy_vm(&machine)
	return bcvm.vm_interpret(&machine, s.module)
}

// _ImportInfo captures a single import declaration for transitive loading.
@private
_ImportInfo :: struct {
	dir:    string, // directory name (the bare import path)
	alias:  string, // namespace used in code (alias if present, else dir)
	offset: u32,    // byte offset of the import for error reporting
}

// _collect_imports scans an AST for ImportDecl nodes and returns their info.
@private
_collect_imports :: proc(ast: ^parser.AST, allocator := context.allocator) -> [dynamic]_ImportInfo {
	imports := make([dynamic]_ImportInfo, allocator)
	for node in ast.nodes {
		decl, ok := node.(parser.Declaration)
		if !ok { continue }
		imp, ok2 := decl.(parser.ImportDecl)
		if !ok2 { continue }
		path, span_start := parser.import_path(imp)
		append(&imports, _ImportInfo{dir = path, alias = parser.import_namespace(imp), offset = span_start})
	}
	return imports
}

// _load_entry_siblings parses every .myr file in source_dir except the entry file
// (skip_file) and merges them into ast as part of the main module. Files in a
// directory form one compilation unit, so siblings of the entry file are visible
// to it (and to each other) unqualified.
@private
_load_entry_siblings :: proc(ast: ^parser.AST, src_bytes_store: ^[dynamic][]byte, source_dir: string, skip_file: string) -> []CompileError {
	file_infos, rd_err := os.read_directory_by_path(source_dir, -1, context.allocator)
	if rd_err != os.ERROR_NONE { return nil }
	defer os.file_info_slice_delete(file_infos, context.allocator)

	for fi in file_infos {
		if fi.type == .Directory { continue }
		if !strings.has_suffix(fi.name, ".myr") { continue }
		if fi.name == skip_file { continue }

		full_path := strings.concatenate([]string{source_dir, "/", fi.name})
		defer delete(full_path)

		src_bytes, read_err := os.read_entire_file_from_path(full_path, context.allocator)
		if read_err != os.ERROR_NONE { continue }
		append(src_bytes_store, src_bytes)

		mod_source := string(src_bytes)
		mod_p   := parser.new_parser(mod_source)
		mod_ast := parser.parse_program(&mod_p)

		if len(mod_p.errors) > 0 {
			errs := make([]CompileError, len(mod_p.errors))
			for e, i in mod_p.errors {
				errs[i] = {
					message = strings.clone(fmt.tprintf("%s: %s", fi.name,
						parser.decode_parser_error_message(&mod_p.errors[i], mod_source))),
					offset  = 0,
				}
			}
			parser.ast_destroy(&mod_ast)
			delete(mod_p.errors)
			return errs
		}
		delete(mod_p.errors)

		// Merged into the main module: left untagged so module_of falls back to MAIN_MODULE.
		parser.ast_merge(ast, &mod_ast)
		parser.ast_destroy(&mod_ast)
	}

	return nil
}

// _module_id_for returns the id of an already-loaded module by directory name.
@private
_module_id_for :: proc(table: ^parser.ModuleTable, dir: string) -> (parser.ModuleId, bool) {
	for name, i in table.names {
		if parser.ModuleId(i) == parser.MAIN_MODULE { continue }
		if name == dir { return parser.ModuleId(i), true }
	}
	return parser.MAIN_MODULE, false
}

// _load_module loads the directory `imp.dir` (relative to source_dir) as a module:
// it reads every .myr file there, merges them into ast (tagging them with the new
// module id), registers the importer's alias, and recurses into the module's own
// imports. A DFS `stack` of directory names in flight detects circular imports.
// src_bytes_store keeps source byte slices alive so token.data views stay valid.
@private
_load_module :: proc(ast: ^parser.AST, table: ^parser.ModuleTable, src_bytes_store: ^[dynamic][]byte, source_dir: string, imp: _ImportInfo, importer: parser.ModuleId, stack: ^[dynamic]string) -> []CompileError {
	// Already loaded? Either a cycle (on the stack) or a benign re-import (a DAG edge).
	if existing, found := _module_id_for(table, imp.dir); found {
		for d in stack {
			if d == imp.dir {
				return _circular_error(stack^, imp.dir, imp.offset)
			}
		}
		table.aliases[importer][imp.alias] = existing
		return nil
	}

	mod := parser.module_new(table, imp.dir)
	table.aliases[importer][imp.alias] = mod
	append(stack, imp.dir)
	defer pop(stack)

	module_dir := strings.concatenate([]string{source_dir, "/", imp.dir})
	defer delete(module_dir)

	file_infos, rd_err := os.read_directory_by_path(module_dir, -1, context.allocator)
	if rd_err != os.ERROR_NONE {
		errs := make([]CompileError, 1)
		errs[0] = {
			message = strings.clone(fmt.tprintf("import '%s': directory not found", imp.dir)),
			offset  = imp.offset,
		}
		return errs
	}
	defer os.file_info_slice_delete(file_infos, context.allocator)

	// Imports discovered in this module's files, recursed into after merging.
	child_imports := make([dynamic]_ImportInfo, context.temp_allocator)

	for fi in file_infos {
		if fi.type == .Directory { continue }
		if !strings.has_suffix(fi.name, ".myr") { continue }

		full_path := strings.concatenate([]string{module_dir, "/", fi.name})
		defer delete(full_path)

		src_bytes, read_err := os.read_entire_file_from_path(full_path, context.allocator)
		if read_err != os.ERROR_NONE { continue }
		// Do NOT free src_bytes — token.data strings are views into it. Ownership
		// transfers to src_bytes_store; freed by myr_free.
		append(src_bytes_store, src_bytes)

		mod_source := string(src_bytes)
		mod_p  := parser.new_parser(mod_source)
		mod_ast := parser.parse_program(&mod_p)

		if len(mod_p.errors) > 0 {
			errs := make([]CompileError, len(mod_p.errors))
			for e, i in mod_p.errors {
				errs[i] = {
					message = strings.clone(fmt.tprintf("%s/%s: %s", imp.dir, fi.name,
						parser.decode_parser_error_message(&mod_p.errors[i], mod_source))),
					offset  = imp.offset,
				}
			}
			parser.ast_destroy(&mod_ast)
			delete(mod_p.errors)
			return errs
		}
		delete(mod_p.errors)

		// Collect this file's imports (alias is relative to THIS module) before merge.
		for child in _collect_imports(&mod_ast, context.temp_allocator) {
			append(&child_imports, child)
		}

		base := parser.ast_merge(ast, &mod_ast)
		parser.module_tag_range(table, base, u32(len(ast.nodes)), mod)
		parser.ast_destroy(&mod_ast)
	}

	// Recurse into the module's own imports (transitive loading + cycle detection).
	for child in child_imports {
		load_errs := _load_module(ast, table, src_bytes_store, source_dir, child, mod, stack)
		if load_errs != nil { return load_errs }
	}

	return nil
}

// _circular_error formats a circular-import error showing the cycle path.
@private
_circular_error :: proc(stack: [dynamic]string, repeated: string, offset: u32) -> []CompileError {
	b := strings.builder_make(context.temp_allocator)
	started := false
	for d in stack {
		if !started && d != repeated { continue }
		started = true
		strings.write_string(&b, d)
		strings.write_string(&b, " -> ")
	}
	strings.write_string(&b, repeated)
	errs := make([]CompileError, 1)
	errs[0] = {
		message = strings.clone(fmt.tprintf("circular import: %s", strings.to_string(b))),
		offset  = offset,
	}
	return errs
}
