// AI_GENERATED: GENERATED BY CLAUDE CODE
package lexer

import "core:testing"

make_lexer :: proc(source: string) -> Lexer {
	return Lexer{source = source, start = 0, current = 0}
}

// is_eof
@(test)
test_is_eof_empty :: proc(t: ^testing.T) {
	l := make_lexer("")
	testing.expect(t, is_eof(&l), "empty source should be EOF")
}

@(test)
test_is_eof_not_empty :: proc(t: ^testing.T) {
	l := make_lexer("a")
	testing.expect(t, !is_eof(&l), "non-empty source should not be EOF")
}

@(test)
test_is_eof_after_advance :: proc(t: ^testing.T) {
	l := make_lexer("a")
	advance(&l)
	testing.expect(t, is_eof(&l), "should be EOF after consuming last char")
}

// peek
@(test)
test_peek_returns_current :: proc(t: ^testing.T) {
	l := make_lexer("abc")
	testing.expect_value(t, peek(&l), byte('a'))
}

@(test)
test_peek_does_not_advance :: proc(t: ^testing.T) {
	l := make_lexer("abc")
	peek(&l)
	peek(&l)
	testing.expect_value(t, l.current, u32(0))
}

@(test)
test_peek_at_eof :: proc(t: ^testing.T) {
	l := make_lexer("")
	testing.expect_value(t, peek(&l), byte(0))
}

// advance
@(test)
test_advance_returns_char :: proc(t: ^testing.T) {
	l := make_lexer("abc")
	ch := advance(&l)
	testing.expect_value(t, ch, byte('a'))
}

@(test)
test_advance_moves_cursor :: proc(t: ^testing.T) {
	l := make_lexer("abc")
	advance(&l)
	testing.expect_value(t, l.current, u32(1))
}

@(test)
test_advance_at_eof :: proc(t: ^testing.T) {
	l := make_lexer("")
	ch := advance(&l)
	testing.expect_value(t, ch, byte(0))
	testing.expect_value(t, l.current, u32(0))
}

// match
@(test)
test_match_correct_char :: proc(t: ^testing.T) {
	l := make_lexer("=")
	ok := match(&l, '=')
	testing.expect(t, ok, "match should succeed on correct char")
	testing.expect_value(t, l.current, u32(1))
}

@(test)
test_match_wrong_char :: proc(t: ^testing.T) {
	l := make_lexer("=")
	ok := match(&l, '!')
	testing.expect(t, !ok, "match should fail on wrong char")
	testing.expect_value(t, l.current, u32(0))
}

@(test)
test_match_at_eof :: proc(t: ^testing.T) {
	l := make_lexer("")
	ok := match(&l, '=')
	testing.expect(t, !ok, "match should fail at EOF")
}

// skip_whitespace
@(test)
test_skip_whitespace_spaces :: proc(t: ^testing.T) {
	l := make_lexer("   abc")
	skip_whitespace(&l)
	testing.expect_value(t, peek(&l), byte('a'))
}

@(test)
test_skip_whitespace_mixed :: proc(t: ^testing.T) {
	l := make_lexer(" \t\n\r abc")
	skip_whitespace(&l)
	testing.expect_value(t, peek(&l), byte('a'))
}

@(test)
test_skip_whitespace_comment :: proc(t: ^testing.T) {
	l := make_lexer("// this is a comment\nabc")
	skip_whitespace(&l)
	testing.expect_value(t, peek(&l), byte('a'))
}

@(test)
test_skip_whitespace_block_comment :: proc(t: ^testing.T) {
	l := make_lexer("/* block comment */abc")
	skip_whitespace(&l)
	testing.expect_value(t, peek(&l), byte('a'))
}

@(test)
test_skip_whitespace_block_comment_multiline :: proc(t: ^testing.T) {
	l := make_lexer("/* line one\n   line two\n*/abc")
	skip_whitespace(&l)
	testing.expect_value(t, peek(&l), byte('a'))
}

@(test)
test_skip_whitespace_block_comment_inline :: proc(t: ^testing.T) {
	// block comment between tokens — lexer lands on next non-whitespace
	l := make_lexer("/* skip */xyz")
	skip_whitespace(&l)
	testing.expect_value(t, peek(&l), byte('x'))
}

@(test)
test_skip_whitespace_block_comment_then_line_comment :: proc(t: ^testing.T) {
	l := make_lexer("/* block */ // line\nabc")
	skip_whitespace(&l)
	testing.expect_value(t, peek(&l), byte('a'))
}

@(test)
test_skip_whitespace_block_comment_unterminated :: proc(t: ^testing.T) {
	// unterminated block comment — lexer should reach EOF without panicking
	l := make_lexer("/* no end")
	skip_whitespace(&l)
	testing.expect(t, is_eof(&l), "unterminated block comment should reach EOF")
}

@(test)
test_skip_whitespace_no_whitespace :: proc(t: ^testing.T) {
	l := make_lexer("abc")
	skip_whitespace(&l)
	testing.expect_value(t, l.current, u32(0))
}

@(test)
test_skip_whitespace_only_whitespace :: proc(t: ^testing.T) {
	l := make_lexer("   ")
	skip_whitespace(&l)
	testing.expect(t, is_eof(&l), "should reach EOF after skipping all whitespace")
}

// next_token — keywords
@(test)
test_keyword_let :: proc(t: ^testing.T) {
	l := make_lexer(KW_LET)
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.LET)
	testing.expect_value(t, tok.data, KW_LET)
}

@(test)
test_keyword_fn :: proc(t: ^testing.T) {
	l := make_lexer(KW_FN)
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.FN)
}

@(test)
test_keyword_if :: proc(t: ^testing.T) {
	l := make_lexer(KW_IF)
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.IF)
}

@(test)
test_keyword_else :: proc(t: ^testing.T) {
	l := make_lexer(KW_ELSE)
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.ELSE)
}

@(test)
test_keyword_true :: proc(t: ^testing.T) {
	l := make_lexer(KW_TRUE)
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.TRUE)
}

@(test)
test_keyword_false :: proc(t: ^testing.T) {
	l := make_lexer(KW_FALSE)
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.FALSE)
}

@(test)
test_keyword_for :: proc(t: ^testing.T) {
	l := make_lexer(KW_FOR)
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.LOOP)
	testing.expect_value(t, tok.data, KW_FOR)
}

@(test)
test_ident_not_keyword :: proc(t: ^testing.T) {
	l := make_lexer("foobar")
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.IDENT)
	testing.expect_value(t, tok.data, "foobar")
}

@(test)
test_keyword_prefix_is_ident :: proc(t: ^testing.T) {
	l := make_lexer("letter")
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.IDENT)
}

// next_token — symbols
@(test)
test_token_plus :: proc(t: ^testing.T) {
	l := make_lexer("+")
	testing.expect_value(t, next_token(&l).kind, TokenType.PLUS)
}

@(test)
test_token_arrow :: proc(t: ^testing.T) {
	l := make_lexer("->")
	testing.expect_value(t, next_token(&l).kind, TokenType.ARROW)
}

@(test)
test_token_eq_eq :: proc(t: ^testing.T) {
	l := make_lexer("==")
	testing.expect_value(t, next_token(&l).kind, TokenType.EQ_EQ)
}

@(test)
test_token_eq :: proc(t: ^testing.T) {
	l := make_lexer("=")
	testing.expect_value(t, next_token(&l).kind, TokenType.EQ)
}

@(test)
test_token_colon_colon :: proc(t: ^testing.T) {
	l := make_lexer("::")
	testing.expect_value(t, next_token(&l).kind, TokenType.COLON_COLON)
}

@(test)
test_token_lt_lt :: proc(t: ^testing.T) {
	l := make_lexer("<<")
	testing.expect_value(t, next_token(&l).kind, TokenType.LT_LT)
}

@(test)
test_token_ellipsis :: proc(t: ^testing.T) {
	l := make_lexer("...")
	testing.expect_value(t, next_token(&l).kind, TokenType.ELLIPSIS)
}

@(test)
test_token_dot :: proc(t: ^testing.T) {
	l := make_lexer(".")
	testing.expect_value(t, next_token(&l).kind, TokenType.DOT)
}

// next_token — literals
@(test)
test_token_int :: proc(t: ^testing.T) {
	l := make_lexer("123")
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.INT)
	testing.expect_value(t, tok.data, "123")
}

@(test)
test_token_float :: proc(t: ^testing.T) {
	l := make_lexer("3.14")
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.FLOAT)
	testing.expect_value(t, tok.data, "3.14")
}

@(test)
test_token_string :: proc(t: ^testing.T) {
	l := make_lexer("\"hello\"")
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.STRING)
}

@(test)
test_token_unterminated_string :: proc(t: ^testing.T) {
	l := make_lexer("\"hello")
	tok := next_token(&l)
	testing.expect_value(t, tok.kind, TokenType.ERROR)
}

// next_token — underscore
@(test)
test_token_underscore :: proc(t: ^testing.T) {
	l := make_lexer("_")
	testing.expect_value(t, next_token(&l).kind, TokenType.UNDERSCORE)
}

// next_token — EOF
@(test)
test_token_eof :: proc(t: ^testing.T) {
	l := make_lexer("")
	testing.expect_value(t, next_token(&l).kind, TokenType.EOF)
}

@(test)
test_token_eof_after_tokens :: proc(t: ^testing.T) {
	l := make_lexer("x")
	next_token(&l)
	testing.expect_value(t, next_token(&l).kind, TokenType.EOF)
}

// next_token — spans
@(test)
test_token_span :: proc(t: ^testing.T) {
	l := make_lexer("let")
	tok := next_token(&l)
	testing.expect_value(t, tok.span.start, u32(0))
	testing.expect_value(t, tok.span.end,   u32(3))
}

@(test)
test_token_span_after_whitespace :: proc(t: ^testing.T) {
	l := make_lexer("   let")
	tok := next_token(&l)
	testing.expect_value(t, tok.span.start, u32(3))
	testing.expect_value(t, tok.span.end,   u32(6))
}
