// AI_GENERATED: GENERATED BY CLAUDE CODE
package bytecode

import "core:testing"
import "../../lexer"

dummy_span :: proc() -> lexer.Span {
	return lexer.Span{start = 0, end = 0}
}

// ---- chunk_write ----

@(test)
test_chunk_write_single_byte :: proc(t: ^testing.T) {
	c := new_chunk()
	defer chunk_free(&c)
	err := chunk_write(&c, 0x01, dummy_span())
	testing.expect(t, err == nil, "write should succeed")
	testing.expect_value(t, len(c.code), 1)
	testing.expect_value(t, c.code[0], u8(0x01))
}

@(test)
test_chunk_write_multiple_bytes :: proc(t: ^testing.T) {
	c := new_chunk()
	defer chunk_free(&c)
	chunk_write(&c, 0x01, dummy_span())
	chunk_write(&c, 0x02, dummy_span())
	chunk_write(&c, 0x03, dummy_span())
	testing.expect_value(t, len(c.code), 3)
	testing.expect_value(t, c.code[2], u8(0x03))
}

@(test)
test_chunk_write_stores_span :: proc(t: ^testing.T) {
	c := new_chunk()
	defer chunk_free(&c)
	span := lexer.Span{start = 5, end = 10}
	chunk_write(&c, 0x01, span)
	testing.expect_value(t, c.spans[0].start, u32(5))
	testing.expect_value(t, c.spans[0].end,   u32(10))
}

// ---- values_equal ----

@(test)
test_values_equal_same_int :: proc(t: ^testing.T) {
	testing.expect(t, values_equal(i64(42), i64(42)), "same int should be equal")
}

@(test)
test_values_equal_different_int :: proc(t: ^testing.T) {
	testing.expect(t, !values_equal(i64(1), i64(2)), "different ints should not be equal")
}

@(test)
test_values_equal_same_float :: proc(t: ^testing.T) {
	testing.expect(t, values_equal(f64(3.14), f64(3.14)), "same float should be equal")
}

@(test)
test_values_equal_same_bool :: proc(t: ^testing.T) {
	testing.expect(t, values_equal(true, true))
	testing.expect(t, !values_equal(true, false))
}

@(test)
test_values_equal_same_string :: proc(t: ^testing.T) {
	testing.expect(t, values_equal("hello", "hello"))
	testing.expect(t, !values_equal("hello", "world"))
}

@(test)
test_values_equal_nil :: proc(t: ^testing.T) {
	testing.expect(t, values_equal(Nil{}, Nil{}))
}

@(test)
test_values_equal_different_types :: proc(t: ^testing.T) {
	testing.expect(t, !values_equal(i64(1), f64(1.0)), "different types should not be equal")
	testing.expect(t, !values_equal(i64(0), false),    "int and bool should not be equal")
}

@(test)
test_values_equal_functions_same_index :: proc(t: ^testing.T) {
	testing.expect(t,  values_equal(Value(FnRef(1)), Value(FnRef(1))), "same FnRef should be equal")
	testing.expect(t, !values_equal(Value(FnRef(1)), Value(FnRef(2))), "different FnRef should not be equal")
}

// ---- chunk_add_constant ----

@(test)
test_add_constant_int :: proc(t: ^testing.T) {
	c := new_chunk()
	defer chunk_free(&c)
	idx, err := chunk_add_constant(&c, i64(42))
	testing.expect(t, err == nil, "should not error")
	testing.expect_value(t, idx, u16(0))
	testing.expect_value(t, c.constants[0].(i64), i64(42))
}

@(test)
test_add_constant_multiple :: proc(t: ^testing.T) {
	c := new_chunk()
	defer chunk_free(&c)
	chunk_add_constant(&c, i64(1))
	chunk_add_constant(&c, i64(2))
	idx, _ := chunk_add_constant(&c, i64(3))
	testing.expect_value(t, idx, u16(2))
	testing.expect_value(t, len(c.constants), 3)
}

@(test)
test_add_constant_deduplicates_int :: proc(t: ^testing.T) {
	c := new_chunk()
	defer chunk_free(&c)
	idx0, _ := chunk_add_constant(&c, i64(42))
	idx1, _ := chunk_add_constant(&c, i64(42))
	testing.expect_value(t, idx0, u16(0))
	testing.expect_value(t, idx1, u16(0))
	testing.expect_value(t, len(c.constants), 1)
}

@(test)
test_add_constant_deduplicates_string :: proc(t: ^testing.T) {
	c := new_chunk()
	defer chunk_free(&c)
	chunk_add_constant(&c, "hello")
	idx, _ := chunk_add_constant(&c, "hello")
	testing.expect_value(t, idx, u16(0))
	testing.expect_value(t, len(c.constants), 1)
}

@(test)
test_add_constant_no_dedup_different_values :: proc(t: ^testing.T) {
	c := new_chunk()
	defer chunk_free(&c)
	chunk_add_constant(&c, i64(1))
	chunk_add_constant(&c, i64(2))
	testing.expect_value(t, len(c.constants), 2)
}

@(test)
test_add_constant_float :: proc(t: ^testing.T) {
	c := new_chunk()
	defer chunk_free(&c)
	chunk_add_constant(&c, f64(3.14))
	testing.expect_value(t, c.constants[0].(f64), f64(3.14))
}

@(test)
test_add_constant_string :: proc(t: ^testing.T) {
	c := new_chunk()
	defer chunk_free(&c)
	chunk_add_constant(&c, "hello")
	testing.expect_value(t, c.constants[0].(string), "hello")
}

// ---- emit ----

@(test)
test_emit_opcode :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit(&bc, .ADD, dummy_span())
	testing.expect_value(t, len(current_chunk(&bc).code), 1)
	testing.expect_value(t, current_chunk(&bc).code[0], u8(Opcode.ADD))
}

// ---- emit_constant ----

@(test)
test_emit_constant_small :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit_constant(&bc, i64(42), dummy_span())
	testing.expect_value(t, len(current_chunk(&bc).code), 2)
	testing.expect_value(t, current_chunk(&bc).code[0], u8(Opcode.CONST))
	testing.expect_value(t, current_chunk(&bc).code[1], u8(0))
	testing.expect_value(t, current_chunk(&bc).constants[0].(i64), i64(42))
}

@(test)
test_emit_constant_two_values :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit_constant(&bc, i64(1), dummy_span())
	emit_constant(&bc, i64(2), dummy_span())
	testing.expect_value(t, len(current_chunk(&bc).code), 4)
	testing.expect_value(t, current_chunk(&bc).code[2], u8(Opcode.CONST))
	testing.expect_value(t, current_chunk(&bc).code[3], u8(1))
}

// ---- emit_jump + patch_jump ----

@(test)
test_emit_jump_writes_placeholder :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	offset, _ := emit_jump(&bc, .JUMP_IF_FALSE, dummy_span())
	testing.expect_value(t, len(current_chunk(&bc).code), 3)
	testing.expect_value(t, current_chunk(&bc).code[0], u8(Opcode.JUMP_IF_FALSE))
	testing.expect_value(t, current_chunk(&bc).code[1], PLACEHOLDER_BYTE_HI)
	testing.expect_value(t, current_chunk(&bc).code[2], PLACEHOLDER_BYTE_LO)
	testing.expect_value(t, offset, u16(1))
}

@(test)
test_patch_jump_writes_correct_offset :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	offset, _ := emit_jump(&bc, .JUMP_IF_FALSE, dummy_span())
	emit_byte(&bc, u8(Opcode.PRINT), dummy_span())
	emit_byte(&bc, u8(Opcode.POP),   dummy_span())
	emit_byte(&bc, u8(Opcode.PRINT), dummy_span())
	emit_byte(&bc, u8(Opcode.POP),   dummy_span())
	patch_jump(&bc, offset)
	hi   := current_chunk(&bc).code[offset]
	lo   := current_chunk(&bc).code[offset + 1]
	dist := u16(hi) << 8 | u16(lo)
	testing.expect_value(t, dist, u16(4))
}

// ---- emit_loop ----

@(test)
test_emit_loop_writes_offset :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	loop_start := u16(len(current_chunk(&bc).code))
	emit_byte(&bc, u8(Opcode.PRINT), dummy_span())
	emit_byte(&bc, u8(Opcode.PRINT), dummy_span())
	emit_byte(&bc, u8(Opcode.PRINT), dummy_span())
	emit_byte(&bc, u8(Opcode.PRINT), dummy_span())
	emit_loop(&bc, loop_start, dummy_span())
	testing.expect_value(t, current_chunk(&bc).code[4], u8(Opcode.LOOP))
	hi   := current_chunk(&bc).code[5]
	lo   := current_chunk(&bc).code[6]
	dist := u16(hi) << 8 | u16(lo)
	testing.expect(t, dist > 0, "loop offset should be non-zero")
}

// ---- hand-encoded chunk: 1 + 2 ----

@(test)
test_hand_encoded_add :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	span := dummy_span()

	emit_constant(&bc, i64(1), span)
	emit_constant(&bc, i64(2), span)
	emit(&bc, .ADD, span)
	emit(&bc, .RETURN, span)

	testing.expect_value(t, len(current_chunk(&bc).code), 6)
	testing.expect_value(t, current_chunk(&bc).constants[0].(i64), i64(1))
	testing.expect_value(t, current_chunk(&bc).constants[1].(i64), i64(2))
	testing.expect_value(t, current_chunk(&bc).code[4], u8(Opcode.ADD))
	testing.expect_value(t, current_chunk(&bc).code[5], u8(Opcode.RETURN))
}
