// AI_GENERATED: GENERATED BY CLAUDE CODE
package bytecode

import "core:testing"
import "../../parser"

// ---- helpers ----

compile_source :: proc(source: string) -> (^Module, []CompilerError) {
	p   := parser.new_parser(source)
	ast := parser.parse_program(&p)
	defer parser.ast_destroy(&ast)
	delete(p.errors)
	return compile(&ast)
}

// ---- compile errors ----

@(test)
test_compile_no_errors :: proc(t: ^testing.T) {
	m, errs := compile_source("function main() { }")
	defer if m != nil do module_free(m)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_produces_function :: proc(t: ^testing.T) {
	m, errs := compile_source("function main() { }")
	defer if m != nil do module_free(m)
	testing.expect(t, len(errs) == 0, "expected no errors")
	testing.expect(t, m != nil, "expected a module")
}

@(test)
test_compile_empty_function_has_return :: proc(t: ^testing.T) {
	m, _ := compile_source("function main() { }")
	defer if m != nil do module_free(m)
	// top-level __main__ chunk (index 0) should end with RETURN
	fn   := m.functions[0]
	last := fn.chunk.code[len(fn.chunk.code) - 2]
	testing.expect_value(t, Opcode(last), Opcode.RETURN)
}

@(test)
test_compile_literal_in_constant_pool :: proc(t: ^testing.T) {
	m, _ := compile_source("function main() { return 42 }")
	defer if m != nil do module_free(m)
	// main is at m.functions[1]; look for 42 in its constant pool
	found := false
	for fn in m.functions {
		if fn == nil { continue }
		for v in fn.chunk.constants {
			if i, ok := v.(i64); ok && i == 42 { found = true }
		}
	}
	testing.expect(t, found, "42 should be in main's constant pool")
}

@(test)
test_compile_true_in_constant_pool :: proc(t: ^testing.T) {
	m, _ := compile_source("function main() { return true }")
	defer if m != nil do module_free(m)
	found := false
	for fn in m.functions {
		if fn == nil { continue }
		for v in fn.chunk.constants {
			if b, ok := v.(bool); ok && b { found = true }
		}
	}
	testing.expect(t, found, "expected bool true in a function's constant pool")
}

@(test)
test_compile_add_uses_add_opcode :: proc(t: ^testing.T) {
	m, _ := compile_source("function main() { return 1 + 2 }")
	defer if m != nil do module_free(m)
	found := false
	for fn in m.functions {
		if fn == nil { continue }
		for b in fn.chunk.code {
			if Opcode(b) == .ADD { found = true }
		}
	}
	testing.expect(t, found, "expected ADD opcode in main")
}

@(test)
test_compile_constant_dedup :: proc(t: ^testing.T) {
	// test dedup directly on a chunk — simpler than searching nested functions
	c := new_bytecode_compiler("test", 0)
	defer compiler_free(&c)
	emit_constant(&c, i64(1), {})
	emit_constant(&c, i64(1), {})   // same value — should dedup
	emit_constant(&c, i64(2), {})
	testing.expect_value(t, len(current_chunk(&c).constants), 2)  // 1 and 2, not 1, 1, 2
}

@(test)
test_compile_function_count :: proc(t: ^testing.T) {
	m, _ := compile_source(`
		function foo() { }
		function bar() { }
		function main() { }
	`)
	defer if m != nil do module_free(m)
	// module.functions has __main__ (idx 0) + foo + bar + main = 4 entries
	non_nil := 0
	for fn in m.functions { if fn != nil { non_nil += 1 } }
	testing.expect_value(t, non_nil, 4)
}

// ---- structs ----

@(test)
test_compile_struct_decl_no_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		struct Point { x: float, y: float }
		function main() { }
	`)
	defer if fn != nil do module_free(fn)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_struct_literal_no_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = 1.0, y = 2.0} }
	`)
	defer if fn != nil do module_free(fn)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_struct_field_access_no_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = 1.0, y = 2.0} return p.x }
	`)
	defer if fn != nil do module_free(fn)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_struct_field_write_no_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = 1.0, y = 2.0} p.x = 99.0 }
	`)
	defer if fn != nil do module_free(fn)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_struct_chained_access_no_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		struct Vec2 { x: float, y: float }
		struct Rect { origin: Vec2, size: Vec2 }
		function main() { let r = Rect{origin = Vec2{x = 1.0, y = 2.0}, size = Vec2{x = 3.0, y = 4.0}} return r.origin.x }
	`)
	defer if fn != nil do module_free(fn)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_struct_unknown_type_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		function main() { let p = NoSuchStruct{x = 1.0} }
	`)
	defer if fn != nil do module_free(fn)
	testing.expect(t, len(errs) > 0, "expected error for undefined struct")
}
