// AI_GENERATED: GENERATED BY CLAUDE CODE
package bytecode

import "core:testing"
import "../../parser"

// ---- helpers ----

compile_source :: proc(source: string) -> (^Function, []CompilerError) {
	p   := parser.new_parser(source)
	ast := parser.parse_program(&p)
	defer parser.ast_destroy(&ast)
	delete(p.errors)
	return compile(&ast)
}

// ---- compile errors ----

@(test)
test_compile_no_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source("function main() { }")
	defer if fn != nil do function_free(fn)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_produces_function :: proc(t: ^testing.T) {
	fn, errs := compile_source("function main() { }")
	defer if fn != nil do function_free(fn)
	testing.expect(t, len(errs) == 0, "expected no errors")
	testing.expect(t, fn != nil, "expected a function")
}

@(test)
test_compile_empty_function_has_return :: proc(t: ^testing.T) {
	fn, _ := compile_source("function main() { }")
	defer if fn != nil do function_free(fn)
	// top-level chunk should end with RETURN <slot_count>
	last := fn.chunk.code[len(fn.chunk.code) - 2]
	testing.expect_value(t, Opcode(last), Opcode.RETURN)
}

@(test)
test_compile_literal_in_constant_pool :: proc(t: ^testing.T) {
	fn, _ := compile_source("function main() { return 42 }")
	defer if fn != nil do function_free(fn)
	// main function is stored as a constant in the top-level chunk
	found := false
	for c in fn.chunk.constants {
		if fn_val, ok := c.(^Function); ok {
			for v in fn_val.chunk.constants {
				if i, ok2 := v.(i64); ok2 && i == 42 {
					found = true
				}
			}
		}
	}
	testing.expect(t, found, "42 should be in main's constant pool")
}

@(test)
test_compile_true_in_constant_pool :: proc(t: ^testing.T) {
	fn, _ := compile_source("function main() { return true }")
	defer if fn != nil do function_free(fn)
	found := false
	for c in fn.chunk.constants {
		if fn_val, ok := c.(^Function); ok {
			for v in fn_val.chunk.constants {
				if b, ok2 := v.(bool); ok2 && b do found = true
			}
		}
	}
	testing.expect(t, found, "expected bool true in main's constant pool")
}

@(test)
test_compile_add_uses_add_opcode :: proc(t: ^testing.T) {
	fn, _ := compile_source("function main() { return 1 + 2 }")
	defer if fn != nil do function_free(fn)
	found := false
	for c in fn.chunk.constants {
		if fn_val, ok := c.(^Function); ok {
			for byte in fn_val.chunk.code {
				if Opcode(byte) == .ADD do found = true
			}
		}
	}
	testing.expect(t, found, "expected ADD opcode in main")
}

@(test)
test_compile_constant_dedup :: proc(t: ^testing.T) {
	// test dedup directly on a chunk — simpler than searching nested functions
	c := new_bytecode_compiler("test", 0)
	defer compiler_free(&c)
	emit_constant(&c, i64(1), {})
	emit_constant(&c, i64(1), {})   // same value — should dedup
	emit_constant(&c, i64(2), {})
	testing.expect_value(t, len(current_chunk(&c).constants), 2)  // 1 and 2, not 1, 1, 2
}

@(test)
test_compile_function_count :: proc(t: ^testing.T) {
	fn, _ := compile_source(`
		function foo() { }
		function bar() { }
		function main() { }
	`)
	defer if fn != nil do function_free(fn)
	count := 0
	for c in fn.chunk.constants {
		if _, ok := c.(^Function); ok do count += 1
	}
	testing.expect_value(t, count, 3)
}

// ---- structs ----

@(test)
test_compile_struct_decl_no_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		struct Point { x: float, y: float }
		function main() { }
	`)
	defer if fn != nil do function_free(fn)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_struct_literal_no_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = 1.0, y = 2.0} }
	`)
	defer if fn != nil do function_free(fn)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_struct_field_access_no_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = 1.0, y = 2.0} return p.x }
	`)
	defer if fn != nil do function_free(fn)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_struct_field_write_no_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = 1.0, y = 2.0} p.x = 99.0 }
	`)
	defer if fn != nil do function_free(fn)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_struct_chained_access_no_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		struct Vec2 { x: float, y: float }
		struct Rect { origin: Vec2, size: Vec2 }
		function main() { let r = Rect{origin = Vec2{x = 1.0, y = 2.0}, size = Vec2{x = 3.0, y = 4.0}} return r.origin.x }
	`)
	defer if fn != nil do function_free(fn)
	testing.expect_value(t, len(errs), 0)
}

@(test)
test_compile_struct_unknown_type_errors :: proc(t: ^testing.T) {
	fn, errs := compile_source(`
		function main() { let p = NoSuchStruct{x = 1.0} }
	`)
	defer if fn != nil do function_free(fn)
	testing.expect(t, len(errs) > 0, "expected error for undefined struct")
}
