// AI_GENERATED: GENERATED BY CLAUDE CODE
package bytecode

import "core:testing"
import "../../lexer"

span_at :: proc(line: u32) -> lexer.Span {
	return lexer.Span{start = line, end = line}
}

// ---- simple_instruction ----

@(test)
test_simple_instruction_returns_next_offset :: proc(t: ^testing.T) {
	result := simple_instruction("ADD", 0)
	testing.expect_value(t, result, 1)
}

@(test)
test_simple_instruction_advances_by_one :: proc(t: ^testing.T) {
	testing.expect_value(t, simple_instruction("ADD",    5), 6)
	testing.expect_value(t, simple_instruction("RETURN", 10), 11)
}

// ---- byte_instruction ----

@(test)
test_byte_instruction_returns_offset_plus_two :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit(&bc, .GET_LOCAL, dummy_span())
	emit_byte(&bc, 3, dummy_span())
	result := byte_instruction("GET_LOCAL", current_chunk(&bc), 0)
	testing.expect_value(t, result, 2)
}

// ---- const_instruction ----

@(test)
test_const_instruction_returns_offset_plus_two :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit_constant(&bc, i64(42), dummy_span())
	result := const_instruction("CONST", current_chunk(&bc), 0)
	testing.expect_value(t, result, 2)
}

// ---- const_long_instruction ----

@(test)
test_const_long_instruction_returns_offset_plus_three :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit(&bc, .CONST_LONG, dummy_span())
	emit_byte(&bc, 0x01, dummy_span())
	emit_byte(&bc, 0x00, dummy_span())
	// manually add a constant at index 256
	for i in 0..<257 {
		chunk_add_constant(current_chunk(&bc), i64(i64(i)))
	}
	result := const_long_instruction("CONST_LONG", current_chunk(&bc), 0)
	testing.expect_value(t, result, 3)
}

// ---- jump_instruction ----

@(test)
test_jump_forward_target :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	// JUMP_IF_FALSE with offset 5
	emit(&bc, .JUMP_IF_FALSE, dummy_span())
	emit_byte(&bc, 0x00, dummy_span())
	emit_byte(&bc, 0x05, dummy_span())
	result := jump_instruction("JUMP_IF_FALSE", 1, current_chunk(&bc), 0)
	// offset = 3 (instruction size) + 5 (jump) = 8
	testing.expect_value(t, result, 3)
}

@(test)
test_loop_backward_target :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	// LOOP with offset 6 (jumping back 6 from after instruction)
	emit(&bc, .LOOP, dummy_span())
	emit_byte(&bc, 0x00, dummy_span())
	emit_byte(&bc, 0x06, dummy_span())
	result := jump_instruction("LOOP", -1, current_chunk(&bc), 0)
	testing.expect_value(t, result, 3)
}

// ---- print_value covers all Value variants ----

@(test)
test_print_value_int :: proc(t: ^testing.T) {
	// just verify it doesn't crash — output goes to stdout
	print_value(i64(42))
}

@(test)
test_print_value_float :: proc(t: ^testing.T) {
	print_value(f64(3.14))
}

@(test)
test_print_value_bool :: proc(t: ^testing.T) {
	print_value(true)
	print_value(false)
}

@(test)
test_print_value_string :: proc(t: ^testing.T) {
	print_value("hello")
}

@(test)
test_print_value_nil :: proc(t: ^testing.T) {
	print_value(Nil{})
}

// ---- disassemble_instruction — all opcodes ----

@(test)
test_disassemble_all_simple_opcodes :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	span := dummy_span()

	simple_ops := []Opcode{
		.ADD, .SUB, .MUL, .DIV, .MOD, .NEGATE,
		.EQ, .NEQ, .LT, .LTE, .GT, .GTE, .NOT,
		.NIL, .TRUE, .FALSE,
		.POP, .PRINT,
	}

	for op in simple_ops {
		emit(&bc, op, span)
	}

	offset := 0
	for op in simple_ops {
		next := disassemble_instruction(current_chunk(&bc), offset)
		testing.expect_value(t, next, offset + 1)
		offset = next
	}
}

@(test)
test_disassemble_const :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit_constant(&bc, i64(99), dummy_span())
	next := disassemble_instruction(current_chunk(&bc), 0)
	testing.expect_value(t, next, 2)
}

@(test)
test_disassemble_get_set_local :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit(&bc, .GET_LOCAL, dummy_span())
	emit_byte(&bc, 0, dummy_span())
	emit(&bc, .SET_LOCAL, dummy_span())
	emit_byte(&bc, 1, dummy_span())
	testing.expect_value(t, disassemble_instruction(current_chunk(&bc), 0), 2)
	testing.expect_value(t, disassemble_instruction(current_chunk(&bc), 2), 4)
}

@(test)
test_disassemble_return :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit(&bc, .RETURN, dummy_span())
	emit_byte(&bc, 1, dummy_span())
	testing.expect_value(t, disassemble_instruction(current_chunk(&bc), 0), 2)
}

@(test)
test_disassemble_jump :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit(&bc, .JUMP, dummy_span())
	emit_byte(&bc, 0x00, dummy_span())
	emit_byte(&bc, 0x04, dummy_span())
	next := disassemble_instruction(current_chunk(&bc), 0)
	testing.expect_value(t, next, 3)
}

@(test)
test_disassemble_loop :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit(&bc, .LOOP, dummy_span())
	emit_byte(&bc, 0x00, dummy_span())
	emit_byte(&bc, 0x04, dummy_span())
	next := disassemble_instruction(current_chunk(&bc), 0)
	testing.expect_value(t, next, 3)
}

@(test)
test_disassemble_unknown_opcode :: proc(t: ^testing.T) {
	bc := new_bytecode_compiler("test", 0)
	defer { fn := compiler_end(&bc); function_free(fn) }
	emit_byte(&bc, 0xFF, dummy_span())
	next := disassemble_instruction(current_chunk(&bc), 0)
	testing.expect_value(t, next, 1)
}
