// AI_GENERATED: GENERATED BY CLAUDE CODE
package parser

import "core:strings"

// ModuleId identifies a module (compilation unit = one directory of .myr files).
// Module 0 is always the entry/main module; its symbols use bare, unmangled names.
ModuleId :: distinct u32

MAIN_MODULE :: ModuleId(0)

// MANGLE_SEP separates a module name from a symbol in a mangled global key.
// It is a NUL byte, which can never appear in a Myr identifier, so mangled keys
// can never collide with bare names or the compiler's "__"-style generic names.
MANGLE_SEP :: "\x00"

// ModuleTable threads module membership through name resolution, the type checker,
// and the bytecode compiler. It is built by the loader (embed) and is a pure
// compile-time structure — nothing here survives into the VM.
ModuleTable :: struct {
	// names[k] is the canonical directory name of module k. names[MAIN_MODULE] is "".
	names:       [dynamic]string,
	// node_module is parallel to AST.nodes (like AST.spans): node_module[i] is the
	// module that node i was parsed from. Read only while walking top-level decls.
	node_module: [dynamic]ModuleId,
	// aliases[k] maps a namespace name visible *inside module k* (the alias from
	// `import "x" as y`, or the bare directory name) to the target module it refers to.
	aliases:     [dynamic]map[string]ModuleId,
}

// module_table_init creates a table with module 0 (main) pre-registered.
module_table_init :: proc() -> ModuleTable {
	t := ModuleTable{
		names       = make([dynamic]string),
		node_module = make([dynamic]ModuleId),
		aliases     = make([dynamic]map[string]ModuleId),
	}
	append(&t.names, "")
	append(&t.aliases, make(map[string]ModuleId))
	return t
}

module_table_destroy :: proc(t: ^ModuleTable) {
	delete(t.names)
	delete(t.node_module)
	for &m in t.aliases { delete(m) }
	delete(t.aliases)
}

// module_new registers a fresh module by directory name and returns its id.
module_new :: proc(t: ^ModuleTable, name: string) -> ModuleId {
	id := ModuleId(len(t.names))
	append(&t.names, name)
	append(&t.aliases, make(map[string]ModuleId))
	return id
}

// module_tag_range records that AST nodes in [base, end) belong to module `mod`.
// Call right after ast_merge with the returned base offset. Any untagged gap below
// `base` is padded as MAIN_MODULE, so the entry program's own nodes never need to be
// tagged explicitly — single-file programs leave node_module empty (zero overhead).
module_tag_range :: proc(t: ^ModuleTable, base: u32, end: u32, mod: ModuleId) {
	for len(t.node_module) < int(base) {
		append(&t.node_module, MAIN_MODULE)
	}
	for len(t.node_module) < int(end) {
		append(&t.node_module, mod)
	}
	for i in int(base)..<int(end) {
		t.node_module[i] = mod
	}
}

// module_of returns the module that owns AST node `idx` (MAIN_MODULE if untagged).
module_of :: proc(t: ^ModuleTable, idx: int) -> ModuleId {
	if idx < 0 || idx >= len(t.node_module) { return MAIN_MODULE }
	return t.node_module[idx]
}

// mangle returns the module-qualified key for a symbol. Module 0 (main) uses the
// bare symbol so single-file programs and generic mangling are byte-for-byte
// unchanged; other modules get "<module name>\x00<symbol>".
mangle :: proc(t: ^ModuleTable, mod: ModuleId, sym: string) -> string {
	if mod == MAIN_MODULE { return sym }
	return strings.concatenate({t.names[mod], MANGLE_SEP, sym}, context.temp_allocator)
}

// demangle strips the module prefix from a mangled key for display in error
// messages, returning just the bare symbol (e.g. "math\x00Vec" → "Vec").
demangle :: proc(sym: string) -> string {
	if i := strings.index(sym, MANGLE_SEP); i >= 0 {
		return sym[i + len(MANGLE_SEP):]
	}
	return sym
}
