// AI_GENERATED: GENERATED BY CLAUDE CODE
package parser

import "core:testing"
import "../lexer"

make_parser :: proc(source: string) -> Parser {
	p := Parser{
		lex = lexer.Lexer{source = source, start = 0, current = 0},
	}
	p.current_token = lexer.next_token(&p.lex)
	return p
}

// peek
@(test)
test_peek_returns_kind :: proc(t: ^testing.T) {
	p := make_parser("let")
	testing.expect_value(t, peek(&p), lexer.TokenType.LET)
}

@(test)
test_peek_does_not_consume :: proc(t: ^testing.T) {
	p := make_parser("let")
	peek(&p)
	peek(&p)
	testing.expect_value(t, peek(&p), lexer.TokenType.LET)
}

@(test)
test_peek_empty_is_eof :: proc(t: ^testing.T) {
	p := make_parser("")
	testing.expect_value(t, peek(&p), lexer.TokenType.EOF)
}

// peek_token
@(test)
test_peek_token_returns_full_token :: proc(t: ^testing.T) {
	p := make_parser("let")
	tok := peek_token(&p)
	testing.expect_value(t, tok.kind, lexer.TokenType.LET)
	testing.expect_value(t, tok.data, lexer.KW_LET)
}

// advance
@(test)
test_advance_returns_current :: proc(t: ^testing.T) {
	p := make_parser("let x")
	tok := advance(&p)
	testing.expect_value(t, tok.kind, lexer.TokenType.LET)
}

@(test)
test_advance_moves_to_next :: proc(t: ^testing.T) {
	p := make_parser("let x")
	advance(&p)
	testing.expect_value(t, peek(&p), lexer.TokenType.IDENT)
}

@(test)
test_advance_at_eof_returns_eof :: proc(t: ^testing.T) {
	p := make_parser("")
	tok := advance(&p)
	testing.expect_value(t, tok.kind, lexer.TokenType.EOF)
}

@(test)
test_advance_past_eof_stays_eof :: proc(t: ^testing.T) {
	p := make_parser("x")
	advance(&p)
	advance(&p)
	testing.expect_value(t, peek(&p), lexer.TokenType.EOF)
}

// expect
@(test)
test_expect_correct_kind :: proc(t: ^testing.T) {
	p := make_parser("let")
	tok := expect(&p, .LET)
	testing.expect_value(t, tok.kind, lexer.TokenType.LET)
	testing.expect_value(t, len(p.errors), 0)
}

@(test)
test_expect_wrong_kind_records_error :: proc(t: ^testing.T) {
	p := make_parser("let")
	defer parser_destroy(&p)
	expect(&p, .IDENT)
	testing.expect_value(t, len(p.errors), 1)
	testing.expect_value(t, p.errors[0].kind, ParserErrorType.UNEXPECTED_TOKEN)
}

@(test)
test_expect_wrong_kind_returns_error_token :: proc(t: ^testing.T) {
	p := make_parser("let")
	defer parser_destroy(&p)
	tok := expect(&p, .IDENT)
	testing.expect_value(t, tok.kind, lexer.TokenType.ERROR)
}

@(test)
test_expect_sequence :: proc(t: ^testing.T) {
	p := make_parser("let x")
	expect(&p, .LET)
	tok := expect(&p, .IDENT)
	testing.expect_value(t, tok.kind, lexer.TokenType.IDENT)
	testing.expect_value(t, len(p.errors), 0)
}

// peek_span
@(test)
test_peek_span_correct :: proc(t: ^testing.T) {
	p := make_parser("let")
	span := peek_span(&p)
	testing.expect_value(t, span.start, u32(0))
	testing.expect_value(t, span.end,   u32(3))
}

@(test)
test_peek_span_after_whitespace :: proc(t: ^testing.T) {
	p := make_parser("   let")
	span := peek_span(&p)
	testing.expect_value(t, span.start, u32(3))
	testing.expect_value(t, span.end,   u32(6))
}

// helpers
parse_source :: proc(source: string) -> (Parser, AST) {
	p   := new_parser(source)
	ast := parse_program(&p)
	delete(p.errors)
	return p, ast
}

destroy_source :: proc(ast: ^AST) {
	ast_destroy(ast)
}

has_decl_kind :: proc(ast: ^AST, $T: typeid) -> bool {
	for node in ast.nodes {
		if decl, ok := node.(Declaration); ok {
			if _, is_t := decl.(T); is_t do return true
		}
	}
	return false
}

has_stmt_kind :: proc(ast: ^AST, $T: typeid) -> bool {
	for node in ast.nodes {
		if stmt, ok := node.(Statement); ok {
			if _, is_t := stmt.(T); is_t do return true
		}
	}
	return false
}

has_expr_kind :: proc(ast: ^AST, $T: typeid) -> bool {
	for node in ast.nodes {
		if expr, ok := node.(Expression); ok {
			if _, is_t := expr.(T); is_t do return true
		}
	}
	return false
}

count_decl_kind :: proc(ast: ^AST, $T: typeid) -> int {
	count := 0
	for node in ast.nodes {
		if decl, ok := node.(Declaration); ok {
			if _, is_t := decl.(T); is_t do count += 1
		}
	}
	return count
}

count_expr_kind :: proc(ast: ^AST, $T: typeid) -> int {
	count := 0
	for node in ast.nodes {
		if expr, ok := node.(Expression); ok {
			if _, is_t := expr.(T); is_t do count += 1
		}
	}
	return count
}

// parse_import_declarations
@(test)
test_parse_import :: proc(t: ^testing.T) {
	_, ast := parse_source(`import "core/fmt"`)
	defer ast_destroy(&ast)
	testing.expect(t, has_decl_kind(&ast, ImportDecl), "expected ImportDecl node")
}

// parse_struct_declarations
@(test)
test_parse_struct :: proc(t: ^testing.T) {
	_, ast := parse_source(`struct Point { x: int, y: int }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_decl_kind(&ast, StructDecl), "expected StructDecl node")
}

@(test)
test_parse_struct_empty :: proc(t: ^testing.T) {
	_, ast := parse_source(`struct Empty {}`)
	defer ast_destroy(&ast)
	testing.expect(t, has_decl_kind(&ast, StructDecl), "expected StructDecl node")
}

// parse_enum_declarations
@(test)
test_parse_enum_simple :: proc(t: ^testing.T) {
	_, ast := parse_source(`enum Color { Red, Green, Blue }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_decl_kind(&ast, EnumDecl), "expected EnumDecl node")
}

@(test)
test_parse_enum_with_fields :: proc(t: ^testing.T) {
	source := `enum Shape { Circle { radius: int }, Rect { width: int, height: int } }`
	_, ast := parse_source(source)
	defer ast_destroy(&ast)
	testing.expect(t, has_decl_kind(&ast, EnumDecl), "expected EnumDecl node")
}

// parse_function_declarations
@(test)
test_parse_fn_empty :: proc(t: ^testing.T) {
	_, ast := parse_source(`function foo() {}`)
	defer ast_destroy(&ast)
	testing.expect(t, has_decl_kind(&ast, FunctionDecl), "expected FunctionDecl node")
}

@(test)
test_parse_fn_with_params :: proc(t: ^testing.T) {
	_, ast := parse_source(`function add(x: int, y: int) -> int { return x }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_decl_kind(&ast, FunctionDecl), "expected FunctionDecl node")
}

@(test)
test_parse_fn_no_errors :: proc(t: ^testing.T) {
	p, ast := parse_source(`function foo() {}`)
	defer ast_destroy(&ast)
	testing.expect_value(t, len(p.errors), 0)
}

// parse_let_stmt
@(test)
test_parse_let :: proc(t: ^testing.T) {
	_, ast := parse_source(`function f() { let x = 42 }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_stmt_kind(&ast, LetStatement), "expected LetStatement node")
}

@(test)
test_parse_let_with_type :: proc(t: ^testing.T) {
	_, ast := parse_source(`function f() { let x: int = 42 }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_stmt_kind(&ast, LetStatement), "expected LetStatement node")
}

// parse_return_stmt
@(test)
test_parse_return_with_value :: proc(t: ^testing.T) {
	_, ast := parse_source(`function f() { return 42 }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_stmt_kind(&ast, ReturnStatement), "expected ReturnStatement node")
}

@(test)
test_parse_return_bare :: proc(t: ^testing.T) {
	_, ast := parse_source(`function f() { return }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_stmt_kind(&ast, ReturnStatement), "expected ReturnStatement node")
}

// parse_expr — literals
@(test)
test_parse_expr_int_literal :: proc(t: ^testing.T) {
	_, ast := parse_source(`function f() { let x = 42 }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_expr_kind(&ast, LiteralExpression), "expected LiteralExpression node")
}

@(test)
test_parse_expr_binary :: proc(t: ^testing.T) {
	_, ast := parse_source(`function f() { let x = 1 + 2 }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_expr_kind(&ast, BinaryExpression), "expected BinaryExpression node")
}

@(test)
test_parse_expr_unary :: proc(t: ^testing.T) {
	_, ast := parse_source(`function f() { let x = -1 }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_expr_kind(&ast, UnaryExpression), "expected UnaryExpression node")
}

@(test)
test_parse_expr_precedence :: proc(t: ^testing.T) {
	_, ast := parse_source(`function f() { let x = 1 + 2 * 3 }`)
	defer ast_destroy(&ast)
	testing.expect_value(t, count_expr_kind(&ast, BinaryExpression), 2)
}

@(test)
test_parse_expr_call :: proc(t: ^testing.T) {
	_, ast := parse_source(`function f() { let x = foo(1, 2) }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_expr_kind(&ast, CallExpression), "expected CallExpression node")
}

@(test)
test_parse_expr_field_access :: proc(t: ^testing.T) {
	_, ast := parse_source(`function f() { let x = a.b }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_expr_kind(&ast, FieldAccessExpression), "expected FieldAccessExpression node")
}

// decode_parser_error_message
@(test)
test_decode_error_unexpected_token :: proc(t: ^testing.T) {
	p := make_parser("let")
	defer parser_destroy(&p)
	expect(&p, .IDENT)
	msg := decode_parser_error_message(&p.errors[0], p.lex.source)
	testing.expect(t, len(msg) > 0, "expected non-empty error message")
}

// parse_program — multiple declarations
@(test)
test_parse_program_multiple_decls :: proc(t: ^testing.T) {
	source := `
		function foo() {}
		function bar() {}
		struct Point { x: int }
	`
	_, ast := parse_source(source)
	defer ast_destroy(&ast)
	testing.expect_value(t, count_decl_kind(&ast, FunctionDecl), 2)
	testing.expect_value(t, count_decl_kind(&ast, StructDecl), 1)
}

@(test)
test_parse_program_unexpected_token_recovers :: proc(t: ^testing.T) {
	p, ast := parse_source(`42 function foo() {}`)
	defer ast_destroy(&ast)
	testing.expect_value(t, len(p.errors), 1)
	testing.expect(t, has_decl_kind(&ast, FunctionDecl), "should recover and parse function after error")
}
