// AI_GENERATED: GENERATED BY CLAUDE CODE
package parser

import "core:testing"
import "../lexer"

parse_fn_source :: proc(source: string) -> (AST, DeclarationIdx) {
	p := new_parser(source)
	ast := parse_program(&p)
	delete(p.errors)
	for node, i in ast.nodes {
		if _, ok := node.(Declaration); ok {
			return ast, DeclarationIdx(i)
		}
	}
	return ast, DeclarationIdx(INVALID_IDX)
}

count_nodes_walker :: proc(ast: ^AST, root: DeclarationIdx) -> int {
	w := walker_init(ast, root)
	defer walker_destroy(&w)
	count := 0
	for !walker_done(&w) {
		walker_next(&w)
		count += 1
	}
	return count
}

has_stmt_kind_walker :: proc(ast: ^AST, root: DeclarationIdx, $T: typeid) -> bool {
	w := walker_init(ast, root)
	defer walker_destroy(&w)
	for !walker_done(&w) {
		node, _ := walker_next(&w)
		if s, ok := node.(Statement); ok {
			if _, is_t := s.(T); is_t do return true
		}
	}
	return false
}

has_expr_kind_walker :: proc(ast: ^AST, root: DeclarationIdx, $T: typeid) -> bool {
	w := walker_init(ast, root)
	defer walker_destroy(&w)
	for !walker_done(&w) {
		node, _ := walker_next(&w)
		if e, ok := node.(Expression); ok {
			if _, is_t := e.(T); is_t do return true
		}
	}
	return false
}

count_expr_kind_walker :: proc(ast: ^AST, root: DeclarationIdx, $T: typeid) -> int {
	w := walker_init(ast, root)
	defer walker_destroy(&w)
	count := 0
	for !walker_done(&w) {
		node, _ := walker_next(&w)
		if e, ok := node.(Expression); ok {
			if _, is_t := e.(T); is_t do count += 1
		}
	}
	return count
}

// walker_init / walker_done
@(test)
test_walker_init_not_done :: proc(t: ^testing.T) {
	ast, root := parse_fn_source(`function f() {}`)
	defer ast_destroy(&ast)
	w := walker_init(&ast, root)
	defer walker_destroy(&w)
	testing.expect(t, !walker_done(&w), "walker should not be done after init")
}

@(test)
test_walker_done_after_full_walk :: proc(t: ^testing.T) {
	ast, root := parse_fn_source(`function f() {}`)
	defer ast_destroy(&ast)
	w := walker_init(&ast, root)
	defer walker_destroy(&w)
	for !walker_done(&w) { walker_next(&w) }
	testing.expect(t, walker_done(&w), "walker should be done after full walk")
}

// walker_next — first node is decl
@(test)
test_walker_first_node_is_decl :: proc(t: ^testing.T) {
	ast, root := parse_fn_source(`function f() {}`)
	defer ast_destroy(&ast)
	w := walker_init(&ast, root)
	defer walker_destroy(&w)
	node, _ := walker_next(&w)
	_, ok := node.(Declaration)
	testing.expect(t, ok, "first node should be a Declaration")
}

// walker visits statements
@(test)
test_walker_visits_let_stmt :: proc(t: ^testing.T) {
	ast, root := parse_fn_source(`function f() { let x = 42 }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_stmt_kind_walker(&ast, root, LetStatement), "should visit LetStatement")
}

@(test)
test_walker_visits_return_stmt :: proc(t: ^testing.T) {
	ast, root := parse_fn_source(`function f() { return 1 }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_stmt_kind_walker(&ast, root, ReturnStatement), "should visit ReturnStatement")
}

// walker visits expressions
@(test)
test_walker_visits_literal :: proc(t: ^testing.T) {
	ast, root := parse_fn_source(`function f() { let x = 99 }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_expr_kind_walker(&ast, root, LiteralExpression), "should visit LiteralExpression")
}

@(test)
test_walker_visits_binary :: proc(t: ^testing.T) {
	ast, root := parse_fn_source(`function f() { let x = 1 + 2 }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_expr_kind_walker(&ast, root, BinaryExpression), "should visit BinaryExpression")
}

@(test)
test_walker_visits_both_binary_children :: proc(t: ^testing.T) {
	ast, root := parse_fn_source(`function f() { let x = 1 + 2 }`)
	defer ast_destroy(&ast)
	testing.expect_value(t, count_expr_kind_walker(&ast, root, LiteralExpression), 2)
}

@(test)
test_walker_visits_call :: proc(t: ^testing.T) {
	ast, root := parse_fn_source(`function f() { let x = foo(1) }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_expr_kind_walker(&ast, root, CallExpression), "should visit CallExpression")
}

@(test)
test_walker_visits_field_access :: proc(t: ^testing.T) {
	ast, root := parse_fn_source(`function f() { let x = a.b }`)
	defer ast_destroy(&ast)
	testing.expect(t, has_expr_kind_walker(&ast, root, FieldAccessExpression), "should visit FieldAccessExpression")
}

// visit_decl — invalid index is a no-op
@(test)
test_visit_decl_invalid_is_noop :: proc(t: ^testing.T) {
	ast, _ := parse_fn_source(`function f() {}`)
	defer ast_destroy(&ast)
	visit_decl(&ast, DeclarationIdx(INVALID_IDX), proc(node: Node, span: lexer.Span) {})
}

@(test)
test_visit_stmt_invalid_is_noop :: proc(t: ^testing.T) {
	ast, _ := parse_fn_source(`function f() {}`)
	defer ast_destroy(&ast)
	visit_stmt(&ast, StatementIdx(INVALID_IDX), proc(node: Node, span: lexer.Span) {})
}

@(test)
test_visit_expr_invalid_is_noop :: proc(t: ^testing.T) {
	ast, _ := parse_fn_source(`function f() {}`)
	defer ast_destroy(&ast)
	visit_expr(&ast, ExpressionIdx(INVALID_IDX), proc(node: Node, span: lexer.Span) {})
}
