// AI_GENERATED: GENERATED BY CLAUDE CODE
package nameresolution

import "core:testing"
import "../../parser"

// ---- helpers ----

resolve :: proc(src: string) -> NRResult {
	p := parser.new_parser(src)
	ast := parser.parse_program(&p)
	return resolve_program(&ast)
}

no_errors :: proc(t: ^testing.T, r: NRResult) {
	testing.expect(t, r.error_count == 0, "expected no errors")
}

has_error :: proc(t: ^testing.T, r: NRResult, substr: string) {
	for i in 0..<int(r.error_count) {
		if contains(r.errors[i].message, substr) do return
	}
	testing.expect(t, false, "expected error not found")
}

contains :: proc(s, sub: string) -> bool {
	if len(sub) == 0 do return true
	if len(sub) > len(s) do return false
	for i in 0..=len(s)-len(sub) {
		if s[i:i+len(sub)] == sub do return true
	}
	return false
}

resolved :: proc(r: NRResult, idx: parser.ExpressionIdx) -> bool {
	_, ok := r.resolutions[idx]
	return ok
}

// ---- diagnostic: verify nr_error mechanism ----

@(test)
test_nr_error_increments_count :: proc(t: ^testing.T) {
	nr := NameResolver{
		scopes = make([dynamic]Scope),
		result = NRResult{resolutions = make(map[parser.ExpressionIdx]DefIdx)},
	}
	defer {
		for scope in nr.scopes { delete(scope) }
		delete(nr.scopes)
		delete(nr.result.resolutions)
	}
	span := parser.ExpressionIdx(0) // unused, just need a span placeholder
	_ = span
	nr_error(&nr, {}, "test error")
	testing.expect_value(t, nr.result.error_count, u16(1))
	testing.expect(t, contains(nr.result.errors[0].message, "test error"), "message should match")
}

// ---- diagnostic: verify lookup misses ----

@(test)
test_lookup_miss :: proc(t: ^testing.T) {
	nr := NameResolver{
		scopes = make([dynamic]Scope),
		result = NRResult{resolutions = make(map[parser.ExpressionIdx]DefIdx)},
	}
	defer {
		for scope in nr.scopes { delete(scope) }
		delete(nr.scopes)
		delete(nr.result.resolutions)
	}
	nr_enter_scope(&nr)
	nr_define(&nr, "main", DefIdx(2))
	_, found := nr_lookup(&nr, "y")
	testing.expect(t, !found, "y should not be found in scope that only has main")
	nr_exit_scope(&nr)
}

@(test)
test_resolve_catches_undefined :: proc(t: ^testing.T) {
	r := resolve(`function main() { let x = y }`)
	defer nr_result_destroy(&r)
	testing.expect(t, r.error_count > 0, "should have at least one error")
}

@(test)
test_ast_structure :: proc(t: ^testing.T) {
	p := parser.new_parser(`function main() { let x = y }`)
	ast := parser.parse_program(&p)
	testing.expect_value(t, len(ast.nodes), 3)
	if len(ast.nodes) < 3 do return
	_, is_expr := ast.nodes[0].(parser.Expression)
	_, is_stmt := ast.nodes[1].(parser.Statement)
	_, is_decl := ast.nodes[2].(parser.Declaration)
	testing.expect(t, is_expr, "node[0] should be Expression")
	testing.expect(t, is_stmt, "node[1] should be Statement")
	testing.expect(t, is_decl, "node[2] should be Declaration")
}

// ---- undefined name ----

@(test)
test_undefined_variable :: proc(t: ^testing.T) {
	r := resolve(`function main() { let x = y }`)
	defer nr_result_destroy(&r)
	has_error(t, r, "undefined")
	has_error(t, r, "'y'")
}

@(test)
test_undefined_function :: proc(t: ^testing.T) {
	r := resolve(`function main() { foo() }`)
	defer nr_result_destroy(&r)
	has_error(t, r, "undefined")
	has_error(t, r, "'foo'")
}

// ---- forward reference ----

@(test)
test_forward_reference :: proc(t: ^testing.T) {
	r := resolve(`
function main() { foo() }
function foo() { }
`)
	defer nr_result_destroy(&r)
	no_errors(t, r)
}

@(test)
test_mutual_recursion :: proc(t: ^testing.T) {
	r := resolve(`
function even(n: i64) -> bool { odd(n) }
function odd(n: i64) -> bool  { even(n) }
`)
	defer nr_result_destroy(&r)
	no_errors(t, r)
}

// ---- let binding ----

@(test)
test_let_binding_resolved :: proc(t: ^testing.T) {
	r := resolve(`function main() { let x = 1 let y = x }`)
	defer nr_result_destroy(&r)
	no_errors(t, r)
}

@(test)
test_let_use_before_define :: proc(t: ^testing.T) {
	r := resolve(`function main() { let x = x }`)
	defer nr_result_destroy(&r)
	has_error(t, r, "undefined")
}

// ---- function params ----

@(test)
test_param_visible_in_body :: proc(t: ^testing.T) {
	r := resolve(`function add(x: i64, y: i64) -> i64 { x + y }`)
	defer nr_result_destroy(&r)
	no_errors(t, r)
}

@(test)
test_param_not_visible_outside :: proc(t: ^testing.T) {
	r := resolve(`
function foo(x: i64) { }
function bar() { x }
`)
	defer nr_result_destroy(&r)
	has_error(t, r, "'x'")
}

// ---- shadowing ----

@(test)
test_inner_scope_shadows_outer :: proc(t: ^testing.T) {
	r := resolve(`
function main() {
	let x = 1
	if true { let x = 2 }
}
`)
	defer nr_result_destroy(&r)
	no_errors(t, r)
}

// ---- for loop ----

@(test)
test_for_init_visible_in_body :: proc(t: ^testing.T) {
	// Note: single-ident post like `i` would be parsed as struct literal `i{}` before the body block.
	// Use `i + 0` to keep post as a plain expression.
	r := resolve(`function main() { for let i = 0; i < 10; i + 0 { } }`)
	defer nr_result_destroy(&r)
	no_errors(t, r)
}

@(test)
test_for_init_not_visible_after :: proc(t: ^testing.T) {
	r := resolve(`function main() { for let i = 0; i < 10; i + 0 { } i }`)
	defer nr_result_destroy(&r)
	has_error(t, r, "'i'")
}

// ---- struct and const ----

@(test)
test_const_decl_resolved :: proc(t: ^testing.T) {
	r := resolve(`
const MAX = 100
function main() { MAX }
`)
	defer nr_result_destroy(&r)
	no_errors(t, r)
}

@(test)
test_struct_name_resolved :: proc(t: ^testing.T) {
	r := resolve(`
struct Point { x: i64, y: i64 }
function main() { Point }
`)
	defer nr_result_destroy(&r)
	no_errors(t, r)
}

// ---- error accumulation ----

@(test)
test_multiple_errors_collected :: proc(t: ^testing.T) {
	r := resolve(`function main() { a b c }`)
	defer nr_result_destroy(&r)
	testing.expect(t, r.error_count >= 3, "expected at least 3 errors")
}
