// AI_GENERATED: GENERATED BY CLAUDE CODE
package vm

import "core:testing"
import bc "../../bytecode"
import "../../../parser"

// ---- helpers ----

run_source :: proc(source: string) -> (Value, Maybe(VMError)) {
	p   := parser.new_parser(source)
	ast := parser.parse_program(&p)
	defer parser.ast_destroy(&ast)
	delete(p.errors)

	fn, errs := bc.compile(&ast)
	if len(errs) > 0 || fn == nil do return Nil{}, nil
	defer bc.function_free(fn)

	machine := new_vm()
	defer destroy_vm(&machine)
	vm_err := vm_interpret(&machine, fn)
	if vm_err != nil do return Nil{}, vm_err
	if machine.stack_top == 0 do return Nil{}, nil
	return machine.stack[machine.stack_top - 1], nil
}

result :: proc(source: string) -> Value {
	val, _ := run_source(source)
	return val
}

// ---- arithmetic ----

@(test)
test_e2e_add :: proc(t: ^testing.T) {
	val := result("function main() { return 1 + 2 }")
	testing.expect_value(t, val.(i64), i64(3))
}

@(test)
test_e2e_sub :: proc(t: ^testing.T) {
	val := result("function main() { return 10 - 3 }")
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_mul :: proc(t: ^testing.T) {
	val := result("function main() { return 4 * 5 }")
	testing.expect_value(t, val.(i64), i64(20))
}

@(test)
test_e2e_div :: proc(t: ^testing.T) {
	val := result("function main() { return 10 / 2 }")
	testing.expect_value(t, val.(i64), i64(5))
}

@(test)
test_e2e_negate :: proc(t: ^testing.T) {
	val := result("function main() { return -5 }")
	testing.expect_value(t, val.(i64), i64(-5))
}

// ---- comparison ----

@(test)
test_e2e_lt_true :: proc(t: ^testing.T) {
	val := result("function main() { return 1 < 2 }")
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_gt_false :: proc(t: ^testing.T) {
	val := result("function main() { return 1 > 2 }")
	testing.expect_value(t, val.(bool), false)
}

@(test)
test_e2e_eq_true :: proc(t: ^testing.T) {
	val := result("function main() { return 42 == 42 }")
	testing.expect_value(t, val.(bool), true)
}

// ---- locals ----

@(test)
test_e2e_local_vars :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let x = 10
			let y = 20
			return x + y
		}
	`)
	testing.expect_value(t, val.(i64), i64(30))
}

@(test)
test_e2e_assignment :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let x = 1
			x = x + 9
			return x
		}
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

// ---- control flow ----

@(test)
test_e2e_if_true_branch :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			if 10 > 5 { return 1 }
			return 0
		}
	`)
	testing.expect_value(t, val.(i64), i64(1))
}

@(test)
test_e2e_if_false_branch :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			if 1 > 5 { return 1 }
			return 0
		}
	`)
	testing.expect_value(t, val.(i64), i64(0))
}

@(test)
test_e2e_for_loop_sum :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let total = 0
			let i = 1
			for i <= 5 {
				total = total + i
				i = i + 1
			}
			return total
		}
	`)
	testing.expect_value(t, val.(i64), i64(15))
}

// ---- functions ----

@(test)
test_e2e_function_call :: proc(t: ^testing.T) {
	val := result(`
		function add(a: int, b: int) -> int { return a + b }
		function main() { return add(3, 4) }
	`)
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_nested_calls :: proc(t: ^testing.T) {
	val := result(`
		function double(x: int) -> int { return x * 2 }
		function main() { return double(double(3)) }
	`)
	testing.expect_value(t, val.(i64), i64(12))
}

@(test)
test_e2e_recursion :: proc(t: ^testing.T) {
	val := result(`
		function factorial(n: int) -> int {
			if n <= 1 { return 1 }
			return n * factorial(n - 1)
		}
		function main() { return factorial(5) }
	`)
	testing.expect_value(t, val.(i64), i64(120))
}

// ---- c-style for ----

@(test)
test_e2e_for_c_style_sum :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let sum = 0
			for let i = 0; i < 5; i = i + 1 {
				sum = sum + i
			}
			return sum
		}
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_for_c_style_break :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let result = 0
			for let i = 0; i < 10; i = i + 1 {
				if i == 5 { break }
				result = i
			}
			return result
		}
	`)
	testing.expect_value(t, val.(i64), i64(4))
}

@(test)
test_e2e_for_c_style_i_not_visible_after :: proc(t: ^testing.T) {
	// i should not be accessible after the loop — outer x should be returned
	val := result(`
		function main() -> int {
			let x = 99
			for let i = 0; i < 3; i = i + 1 { }
			return x
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

// ---- break / continue ----

@(test)
test_e2e_break :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let i = 0
			for i < 10 {
				if i == 5 { break }
				i = i + 1
			}
			return i
		}
	`)
	testing.expect_value(t, val.(i64), i64(5))
}

@(test)
test_e2e_continue :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let sum = 0
			let i = 0
			for i < 10 {
				i = i + 1
				if i % 2 == 0 { continue }
				sum = sum + i
			}
			return sum
		}
	`)
	// sum of odd numbers 1+3+5+7+9 = 25
	testing.expect_value(t, val.(i64), i64(25))
}

@(test)
test_e2e_break_with_locals :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let result = 0
			let i = 0
			for i < 10 {
				let x = i * 2
				if x >= 8 { break }
				result = x
				i = i + 1
			}
			return result
		}
	`)
	// last x before x>=8: x=6 (i=3), next i=4 -> x=8 -> break
	testing.expect_value(t, val.(i64), i64(6))
}

// ---- strings ----

@(test)
test_e2e_string_literal :: proc(t: ^testing.T) {
	val := result(`function main() { return "hello" }`)
	testing.expect_value(t, val.(string), "hello")
}

@(test)
test_e2e_string_eq :: proc(t: ^testing.T) {
	val := result(`function main() { return "abc" == "abc" }`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_string_neq :: proc(t: ^testing.T) {
	val := result(`function main() { return "abc" == "xyz" }`)
	testing.expect_value(t, val.(bool), false)
}

@(test)
test_e2e_string_escape_newline :: proc(t: ^testing.T) {
	val := result(`function main() { return "a\nb" }`)
	testing.expect_value(t, val.(string), "a\nb")
}

@(test)
test_e2e_string_escape_tab :: proc(t: ^testing.T) {
	val := result(`function main() { return "a\tb" }`)
	testing.expect_value(t, val.(string), "a\tb")
}

@(test)
test_e2e_string_escape_backslash :: proc(t: ^testing.T) {
	val := result(`function main() { return "a\\b" }`)
	testing.expect_value(t, val.(string), "a\\b")
}

@(test)
test_e2e_string_escape_quote :: proc(t: ^testing.T) {
	val := result(`function main() { return "say \"hi\"" }`)
	testing.expect_value(t, val.(string), "say \"hi\"")
}

@(test)
test_e2e_string_escape_in_condition :: proc(t: ^testing.T) {
	// escaped string compares equal to the decoded value
	val := result(`
		function main() -> bool {
			let s = "hello\nworld"
			return s == "hello\nworld"
		}
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_string_no_escape_fast_path :: proc(t: ^testing.T) {
	// plain string with no backslash takes the fast path
	val := result(`function main() { return "no escapes here" }`)
	testing.expect_value(t, val.(string), "no escapes here")
}

// ---- constants ----

@(test)
test_e2e_const_int :: proc(t: ^testing.T) {
	val := result(`
		const N = 42
		function main() { return N }
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_const_float :: proc(t: ^testing.T) {
	val := result(`
		const F = 3.14
		function main() { return F }
	`)
	testing.expect_value(t, val.(f64), f64(3.14))
}

@(test)
test_e2e_const_bool :: proc(t: ^testing.T) {
	val := result(`
		const FLAG = true
		function main() { return FLAG }
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_const_string :: proc(t: ^testing.T) {
	val := result(`
		const MSG = "hello"
		function main() { return MSG }
	`)
	testing.expect_value(t, val.(string), "hello")
}

@(test)
test_e2e_const_folded_add :: proc(t: ^testing.T) {
	val := result(`
		const A = 10
		const B = 20
		const C = A + B
		function main() { return C }
	`)
	testing.expect_value(t, val.(i64), i64(30))
}

@(test)
test_e2e_const_folded_arithmetic :: proc(t: ^testing.T) {
	val := result(`
		const MAX  = 100
		const HALF = MAX / 2
		const OFF  = HALF - 5
		function main() { return OFF }
	`)
	testing.expect_value(t, val.(i64), i64(45))
}

@(test)
test_e2e_const_negative :: proc(t: ^testing.T) {
	val := result(`
		const NEG = -7
		function main() { return NEG }
	`)
	testing.expect_value(t, val.(i64), i64(-7))
}

@(test)
test_e2e_const_in_loop_bound :: proc(t: ^testing.T) {
	val := result(`
		const LIMIT = 5
		function main() -> int {
			let sum = 0
			let i = 0
			for i < LIMIT {
				sum = sum + i
				i = i + 1
			}
			return sum
		}
	`)
	// 0+1+2+3+4 = 10
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_const_in_condition :: proc(t: ^testing.T) {
	val := result(`
		const THRESHOLD = 10
		function main() -> bool {
			let x = 5
			return x < THRESHOLD
		}
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_const_visible_in_function :: proc(t: ^testing.T) {
	val := result(`
		const BASE = 100
		function add_base(n: int) -> int {
			return n + BASE
		}
		function main() { return add_base(5) }
	`)
	testing.expect_value(t, val.(i64), i64(105))
}

// ---- local constants ----

@(test)
test_e2e_local_const_int :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const N = 99
			return N
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

@(test)
test_e2e_local_const_folded :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const A = 6
			const B = A * 7
			return B
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_local_const_in_loop :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const LIMIT = 5
			let sum = 0
			let i = 0
			for i < LIMIT {
				sum = sum + i
				i = i + 1
			}
			return sum
		}
	`)
	// 0+1+2+3+4 = 10
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_local_const_in_condition :: proc(t: ^testing.T) {
	val := result(`
		function main() -> bool {
			const THRESHOLD = 100
			let x = 50
			return x < THRESHOLD
		}
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_local_const_shadows_global :: proc(t: ^testing.T) {
	val := result(`
		const X = 1
		function main() -> int {
			const X = 2
			return X
		}
	`)
	testing.expect_value(t, val.(i64), i64(2))
}

@(test)
test_e2e_local_const_mixed_with_let :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const STEP = 3
			let total = 0
			let i = 0
			for i < 9 {
				total = total + STEP
				i = i + STEP
			}
			return total
		}
	`)
	// 3 iterations: i=0,3,6 → total=3,6,9
	testing.expect_value(t, val.(i64), i64(9))
}

// ---- runtime errors ----

@(test)
test_e2e_division_by_zero :: proc(t: ^testing.T) {
	_, err := run_source("function main() { return 1 / 0 }")
	testing.expect_value(t, err, Maybe(VMError)(.DIVISION_BY_ZERO))
}
