// AI_GENERATED: GENERATED BY CLAUDE CODE
package vm

import "core:testing"
import "core:strings"
import bc "../../bytecode"
import "../../../parser"

// ---- helpers ----

run_source :: proc(source: string, stdin_data: string = "") -> (Value, Maybe(VMError)) {
	p   := parser.new_parser(source)
	ast := parser.parse_program(&p)
	defer parser.ast_destroy(&ast)
	delete(p.errors)

	fn, errs := bc.compile(&ast)
	if len(errs) > 0 || fn == nil do return Nil{}, nil
	defer bc.function_free(fn)

	machine := new_vm()
	defer destroy_vm(&machine)
	if len(stdin_data) > 0 {
		sr: strings.Reader
		machine.stdin = strings.to_reader(&sr, stdin_data)
	}
	vm_err := vm_interpret(&machine, fn)
	if vm_err != nil do return Nil{}, vm_err
	if machine.stack_top == 0 do return Nil{}, nil
	return machine.stack[machine.stack_top - 1], nil
}

result :: proc(source: string) -> Value {
	val, _ := run_source(source)
	return val
}

result_with_stdin :: proc(source: string, stdin_data: string) -> Value {
	val, _ := run_source(source, stdin_data)
	return val
}

// ---- arithmetic ----

@(test)
test_e2e_add :: proc(t: ^testing.T) {
	val := result("function main() { return 1 + 2 }")
	testing.expect_value(t, val.(i64), i64(3))
}

@(test)
test_e2e_sub :: proc(t: ^testing.T) {
	val := result("function main() { return 10 - 3 }")
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_mul :: proc(t: ^testing.T) {
	val := result("function main() { return 4 * 5 }")
	testing.expect_value(t, val.(i64), i64(20))
}

@(test)
test_e2e_div :: proc(t: ^testing.T) {
	val := result("function main() { return 10 / 2 }")
	testing.expect_value(t, val.(i64), i64(5))
}

@(test)
test_e2e_negate :: proc(t: ^testing.T) {
	val := result("function main() { return -5 }")
	testing.expect_value(t, val.(i64), i64(-5))
}

// ---- comparison ----

@(test)
test_e2e_lt_true :: proc(t: ^testing.T) {
	val := result("function main() { return 1 < 2 }")
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_gt_false :: proc(t: ^testing.T) {
	val := result("function main() { return 1 > 2 }")
	testing.expect_value(t, val.(bool), false)
}

@(test)
test_e2e_eq_true :: proc(t: ^testing.T) {
	val := result("function main() { return 42 == 42 }")
	testing.expect_value(t, val.(bool), true)
}

// ---- locals ----

@(test)
test_e2e_local_vars :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let x = 10
			let y = 20
			return x + y
		}
	`)
	testing.expect_value(t, val.(i64), i64(30))
}

@(test)
test_e2e_assignment :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let x = 1
			x = x + 9
			return x
		}
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

// ---- control flow ----

@(test)
test_e2e_if_true_branch :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			if 10 > 5 { return 1 }
			return 0
		}
	`)
	testing.expect_value(t, val.(i64), i64(1))
}

@(test)
test_e2e_if_false_branch :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			if 1 > 5 { return 1 }
			return 0
		}
	`)
	testing.expect_value(t, val.(i64), i64(0))
}

@(test)
test_e2e_for_loop_sum :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let total = 0
			let i = 1
			for i <= 5 {
				total = total + i
				i = i + 1
			}
			return total
		}
	`)
	testing.expect_value(t, val.(i64), i64(15))
}

// ---- functions ----

@(test)
test_e2e_function_call :: proc(t: ^testing.T) {
	val := result(`
		function add(a: int, b: int) -> int { return a + b }
		function main() { return add(3, 4) }
	`)
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_nested_calls :: proc(t: ^testing.T) {
	val := result(`
		function double(x: int) -> int { return x * 2 }
		function main() { return double(double(3)) }
	`)
	testing.expect_value(t, val.(i64), i64(12))
}

@(test)
test_e2e_recursion :: proc(t: ^testing.T) {
	val := result(`
		function factorial(n: int) -> int {
			if n <= 1 { return 1 }
			return n * factorial(n - 1)
		}
		function main() { return factorial(5) }
	`)
	testing.expect_value(t, val.(i64), i64(120))
}

// ---- c-style for ----

@(test)
test_e2e_for_c_style_sum :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let sum = 0
			for let i = 0; i < 5; i = i + 1 {
				sum = sum + i
			}
			return sum
		}
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_for_c_style_break :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let result = 0
			for let i = 0; i < 10; i = i + 1 {
				if i == 5 { break }
				result = i
			}
			return result
		}
	`)
	testing.expect_value(t, val.(i64), i64(4))
}

@(test)
test_e2e_for_c_style_i_not_visible_after :: proc(t: ^testing.T) {
	// i should not be accessible after the loop — outer x should be returned
	val := result(`
		function main() -> int {
			let x = 99
			for let i = 0; i < 3; i = i + 1 { }
			return x
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

// ---- break / continue ----

@(test)
test_e2e_break :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let i = 0
			for i < 10 {
				if i == 5 { break }
				i = i + 1
			}
			return i
		}
	`)
	testing.expect_value(t, val.(i64), i64(5))
}

@(test)
test_e2e_continue :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let sum = 0
			let i = 0
			for i < 10 {
				i = i + 1
				if i % 2 == 0 { continue }
				sum = sum + i
			}
			return sum
		}
	`)
	// sum of odd numbers 1+3+5+7+9 = 25
	testing.expect_value(t, val.(i64), i64(25))
}

@(test)
test_e2e_break_with_locals :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let result = 0
			let i = 0
			for i < 10 {
				let x = i * 2
				if x >= 8 { break }
				result = x
				i = i + 1
			}
			return result
		}
	`)
	// last x before x>=8: x=6 (i=3), next i=4 -> x=8 -> break
	testing.expect_value(t, val.(i64), i64(6))
}

// ---- strings ----

@(test)
test_e2e_string_literal :: proc(t: ^testing.T) {
	val := result(`function main() { return "hello" }`)
	testing.expect_value(t, val.(string), "hello")
}

@(test)
test_e2e_string_eq :: proc(t: ^testing.T) {
	val := result(`function main() { return "abc" == "abc" }`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_string_neq :: proc(t: ^testing.T) {
	val := result(`function main() { return "abc" == "xyz" }`)
	testing.expect_value(t, val.(bool), false)
}

@(test)
test_e2e_string_escape_newline :: proc(t: ^testing.T) {
	val := result(`function main() { return "a\nb" }`)
	testing.expect_value(t, val.(string), "a\nb")
}

@(test)
test_e2e_string_escape_tab :: proc(t: ^testing.T) {
	val := result(`function main() { return "a\tb" }`)
	testing.expect_value(t, val.(string), "a\tb")
}

@(test)
test_e2e_string_escape_backslash :: proc(t: ^testing.T) {
	val := result(`function main() { return "a\\b" }`)
	testing.expect_value(t, val.(string), "a\\b")
}

@(test)
test_e2e_string_escape_quote :: proc(t: ^testing.T) {
	val := result(`function main() { return "say \"hi\"" }`)
	testing.expect_value(t, val.(string), "say \"hi\"")
}

@(test)
test_e2e_string_escape_in_condition :: proc(t: ^testing.T) {
	// escaped string compares equal to the decoded value
	val := result(`
		function main() -> bool {
			let s = "hello\nworld"
			return s == "hello\nworld"
		}
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_string_no_escape_fast_path :: proc(t: ^testing.T) {
	// plain string with no backslash takes the fast path
	val := result(`function main() { return "no escapes here" }`)
	testing.expect_value(t, val.(string), "no escapes here")
}

// ---- constants ----

@(test)
test_e2e_const_int :: proc(t: ^testing.T) {
	val := result(`
		const N = 42
		function main() { return N }
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_const_float :: proc(t: ^testing.T) {
	val := result(`
		const F = 3.14
		function main() { return F }
	`)
	testing.expect_value(t, val.(f64), f64(3.14))
}

@(test)
test_e2e_const_bool :: proc(t: ^testing.T) {
	val := result(`
		const FLAG = true
		function main() { return FLAG }
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_const_string :: proc(t: ^testing.T) {
	val := result(`
		const MSG = "hello"
		function main() { return MSG }
	`)
	testing.expect_value(t, val.(string), "hello")
}

@(test)
test_e2e_const_folded_add :: proc(t: ^testing.T) {
	val := result(`
		const A = 10
		const B = 20
		const C = A + B
		function main() { return C }
	`)
	testing.expect_value(t, val.(i64), i64(30))
}

@(test)
test_e2e_const_folded_arithmetic :: proc(t: ^testing.T) {
	val := result(`
		const MAX  = 100
		const HALF = MAX / 2
		const OFF  = HALF - 5
		function main() { return OFF }
	`)
	testing.expect_value(t, val.(i64), i64(45))
}

@(test)
test_e2e_const_negative :: proc(t: ^testing.T) {
	val := result(`
		const NEG = -7
		function main() { return NEG }
	`)
	testing.expect_value(t, val.(i64), i64(-7))
}

@(test)
test_e2e_const_in_loop_bound :: proc(t: ^testing.T) {
	val := result(`
		const LIMIT = 5
		function main() -> int {
			let sum = 0
			let i = 0
			for i < LIMIT {
				sum = sum + i
				i = i + 1
			}
			return sum
		}
	`)
	// 0+1+2+3+4 = 10
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_const_in_condition :: proc(t: ^testing.T) {
	val := result(`
		const THRESHOLD = 10
		function main() -> bool {
			let x = 5
			return x < THRESHOLD
		}
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_const_visible_in_function :: proc(t: ^testing.T) {
	val := result(`
		const BASE = 100
		function add_base(n: int) -> int {
			return n + BASE
		}
		function main() { return add_base(5) }
	`)
	testing.expect_value(t, val.(i64), i64(105))
}

// ---- local constants ----

@(test)
test_e2e_local_const_int :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const N = 99
			return N
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

@(test)
test_e2e_local_const_folded :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const A = 6
			const B = A * 7
			return B
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_local_const_in_loop :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const LIMIT = 5
			let sum = 0
			let i = 0
			for i < LIMIT {
				sum = sum + i
				i = i + 1
			}
			return sum
		}
	`)
	// 0+1+2+3+4 = 10
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_local_const_in_condition :: proc(t: ^testing.T) {
	val := result(`
		function main() -> bool {
			const THRESHOLD = 100
			let x = 50
			return x < THRESHOLD
		}
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_local_const_shadows_global :: proc(t: ^testing.T) {
	val := result(`
		const X = 1
		function main() -> int {
			const X = 2
			return X
		}
	`)
	testing.expect_value(t, val.(i64), i64(2))
}

@(test)
test_e2e_local_const_mixed_with_let :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const STEP = 3
			let total = 0
			let i = 0
			for i < 9 {
				total = total + STEP
				i = i + STEP
			}
			return total
		}
	`)
	// 3 iterations: i=0,3,6 → total=3,6,9
	testing.expect_value(t, val.(i64), i64(9))
}

// ---- first-class functions / callbacks ----

@(test)
test_e2e_fn_passed_as_arg :: proc(t: ^testing.T) {
	val := result(`
		function double(x: int) -> int { return x * 2 }
		function apply(f: (int) -> int, x: int) -> int { return f(x) }
		function main() { return apply(double, 5) }
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_fn_stored_in_let :: proc(t: ^testing.T) {
	val := result(`
		function square(x: int) -> int { return x * x }
		function main() -> int {
			let f = square
			return f(6)
		}
	`)
	testing.expect_value(t, val.(i64), i64(36))
}

@(test)
test_e2e_fn_called_in_loop :: proc(t: ^testing.T) {
	val := result(`
		function double(x: int) -> int { return x * 2 }
		function sum_with(f: (int) -> int, n: int) -> int {
			let total = 0
			let i = 0
			for i < n {
				total += f(i)
				i += 1
			}
			return total
		}
		function main() { return sum_with(double, 5) }
	`)
	// double(0)+double(1)+double(2)+double(3)+double(4) = 0+2+4+6+8 = 20
	testing.expect_value(t, val.(i64), i64(20))
}

@(test)
test_e2e_fn_passed_to_multiple_callers :: proc(t: ^testing.T) {
	val := result(`
		function inc(x: int) -> int { return x + 1 }
		function apply(f: (int) -> int, x: int) -> int { return f(x) }
		function main() -> int {
			let a = apply(inc, 10)
			let b = apply(inc, a)
			return b
		}
	`)
	testing.expect_value(t, val.(i64), i64(12))
}

@(test)
test_e2e_two_fn_args :: proc(t: ^testing.T) {
	val := result(`
		function add(a: int, b: int) -> int { return a + b }
		function mul(a: int, b: int) -> int { return a * b }
		function combine(f: (int, int) -> int, g: (int, int) -> int, a: int, b: int) -> int {
			return f(a, b) + g(a, b)
		}
		function main() { return combine(add, mul, 3, 4) }
	`)
	// add(3,4) + mul(3,4) = 7 + 12 = 19
	testing.expect_value(t, val.(i64), i64(19))
}

@(test)
test_e2e_fn_returned_from_fn :: proc(t: ^testing.T) {
	val := result(`
		function double(x: int) -> int { return x * 2 }
		function get_fn(which: int) -> (int) -> int {
			return double
		}
		function main() -> int {
			let f = get_fn(0)
			return f(7)
		}
	`)
	testing.expect_value(t, val.(i64), i64(14))
}

// ---- input ----

@(test)
test_e2e_input_returns_string :: proc(t: ^testing.T) {
	val := result_with_stdin(`
		function main() { return input() }
	`, "hello\n")
	testing.expect_value(t, val.(string), "hello")
}

@(test)
test_e2e_input_strips_newline :: proc(t: ^testing.T) {
	val := result_with_stdin(`
		function main() { return input() }
	`, "world\n")
	testing.expect_value(t, val.(string), "world")
}

@(test)
test_e2e_input_with_prompt :: proc(t: ^testing.T) {
	// prompt is printed to stdout — just verify the return value is correct
	val := result_with_stdin(`
		function main() { return input("name: ") }
	`, "myr\n")
	testing.expect_value(t, val.(string), "myr")
}

@(test)
test_e2e_input_eq :: proc(t: ^testing.T) {
	val := result_with_stdin(`
		function main() -> bool {
			let s = input()
			return s == "yes"
		}
	`, "yes\n")
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_input_multiple :: proc(t: ^testing.T) {
	// second input call reads the next line
	val := result_with_stdin(`
		function main() -> int {
			let a = input()
			let b = input()
			let ok = 0
			if a == "foo" { ok = ok + 1 }
			if b == "bar" { ok = ok + 1 }
			return ok
		}
	`, "foo\nbar\n")
	testing.expect_value(t, val.(i64), i64(2))
}

// ---- runtime errors ----

@(test)
test_e2e_division_by_zero :: proc(t: ^testing.T) {
	_, err := run_source("function main() { return 1 / 0 }")
	testing.expect_value(t, err, Maybe(VMError)(.DIVISION_BY_ZERO))
}

// ---- bit shift ----

@(test)
test_e2e_shl_basic :: proc(t: ^testing.T) {
	val := result("function main() { return 1 << 3 }")
	testing.expect_value(t, val.(i64), i64(8))
}

@(test)
test_e2e_shr_basic :: proc(t: ^testing.T) {
	val := result("function main() { return 16 >> 2 }")
	testing.expect_value(t, val.(i64), i64(4))
}

@(test)
test_e2e_shl_zero :: proc(t: ^testing.T) {
	val := result("function main() { return 5 << 0 }")
	testing.expect_value(t, val.(i64), i64(5))
}

@(test)
test_e2e_shr_to_zero :: proc(t: ^testing.T) {
	val := result("function main() { return 1 >> 1 }")
	testing.expect_value(t, val.(i64), i64(0))
}

@(test)
test_e2e_shl_precedence_add :: proc(t: ^testing.T) {
	// + binds tighter: (1 + 2) << 1 = 6, not 1 + (2 << 1) = 5
	val := result("function main() { return 1 + 2 << 1 }")
	testing.expect_value(t, val.(i64), i64(6))
}

@(test)
test_e2e_shr_precedence_mul :: proc(t: ^testing.T) {
	// * binds tighter: 8 >> (1 * 2) = 2
	val := result("function main() { return 8 >> 1 * 2 }")
	testing.expect_value(t, val.(i64), i64(2))
}

@(test)
test_e2e_shl_variable :: proc(t: ^testing.T) {
	val := result(`function main() {
		let n = 4
		return n << 2
	}`)
	testing.expect_value(t, val.(i64), i64(16))
}

@(test)
test_e2e_shr_variable :: proc(t: ^testing.T) {
	val := result(`function main() {
		let n = 64
		return n >> 3
	}`)
	testing.expect_value(t, val.(i64), i64(8))
}

@(test)
test_e2e_shift_in_loop :: proc(t: ^testing.T) {
	// sum powers of 2: 1+2+4+8+16 = 31
	val := result(`function main() {
		let sum = 0
		let i = 0
		for i < 5 {
			sum += 1 << i
			i += 1
		}
		return sum
	}`)
	testing.expect_value(t, val.(i64), i64(31))
}

@(test)
test_e2e_shift_comparison :: proc(t: ^testing.T) {
	// shift has lower precedence than comparison? No — shift > comparison
	// (8 >> 1) > 3  =  4 > 3  = true
	val := result("function main() { return 8 >> 1 > 3 }")
	testing.expect_value(t, val.(bool), true)
}
