// AI_GENERATED: GENERATED BY CLAUDE CODE
package vm

import "core:testing"
import "core:strings"
import bc "../../bytecode"
import "../../../parser"
import nr "../../../tree-walkers/nameresolution"
import tc "../../../tree-walkers/typechecker"

// ---- helpers ----

run_source :: proc(source: string, stdin_data: string = "") -> (Value, Maybe(VMError)) {
	p   := parser.new_parser(source)
	ast := parser.parse_program(&p)
	defer parser.ast_destroy(&ast)
	delete(p.errors)

	nrr := nr.resolve_program(&ast)
	defer nr.nr_result_destroy(&nrr)

	tcr: tc.TypecheckResult
	if nrr.error_count == 0 {
		tcr = tc.typecheck(&ast, &nrr)
	}
	defer if tcr.types != nil { tc.tc_result_destroy(&tcr) }

	fn, errs := bc.compile(&ast, tcr.types, tcr.type_table[:])
	if len(errs) > 0 || fn == nil do return Nil{}, nil
	defer bc.function_free(fn)

	machine := new_vm()
	defer destroy_vm(&machine)
	if len(stdin_data) > 0 {
		sr: strings.Reader
		machine.stdin = strings.to_reader(&sr, stdin_data)
	}
	vm_err := vm_interpret(&machine, fn)
	if vm_err != nil do return Nil{}, vm_err
	if machine.stack_top == 0 do return Nil{}, nil
	return machine.stack[machine.stack_top - 1], nil
}

result :: proc(source: string) -> Value {
	val, _ := run_source(source)
	return val
}

result_with_stdin :: proc(source: string, stdin_data: string) -> Value {
	val, _ := run_source(source, stdin_data)
	return val
}

// typecheck_error_count runs parse → name resolution → type check and returns
// the number of type errors. Used to verify that invalid programs are rejected.
typecheck_error_count :: proc(source: string) -> int {
	p   := parser.new_parser(source)
	ast := parser.parse_program(&p)
	defer parser.ast_destroy(&ast)
	if len(p.errors) > 0 { delete(p.errors); return 1 }
	delete(p.errors)

	nrr := nr.resolve_program(&ast)
	defer nr.nr_result_destroy(&nrr)
	if nrr.error_count > 0 do return int(nrr.error_count)

	tcr := tc.typecheck(&ast, &nrr)
	defer tc.tc_result_destroy(&tcr)
	return int(tcr.error_count)
}

// ---- arithmetic ----

@(test)
test_e2e_add :: proc(t: ^testing.T) {
	val := result("function main() { return 1 + 2 }")
	testing.expect_value(t, val.(i64), i64(3))
}

@(test)
test_e2e_sub :: proc(t: ^testing.T) {
	val := result("function main() { return 10 - 3 }")
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_mul :: proc(t: ^testing.T) {
	val := result("function main() { return 4 * 5 }")
	testing.expect_value(t, val.(i64), i64(20))
}

@(test)
test_e2e_div :: proc(t: ^testing.T) {
	val := result("function main() { return 10 / 2 }")
	testing.expect_value(t, val.(i64), i64(5))
}

@(test)
test_e2e_negate :: proc(t: ^testing.T) {
	val := result("function main() { return -5 }")
	testing.expect_value(t, val.(i64), i64(-5))
}

// ---- comparison ----

@(test)
test_e2e_lt_true :: proc(t: ^testing.T) {
	val := result("function main() { return 1 < 2 }")
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_gt_false :: proc(t: ^testing.T) {
	val := result("function main() { return 1 > 2 }")
	testing.expect_value(t, val.(bool), false)
}

@(test)
test_e2e_eq_true :: proc(t: ^testing.T) {
	val := result("function main() { return 42 == 42 }")
	testing.expect_value(t, val.(bool), true)
}

// ---- locals ----

@(test)
test_e2e_local_vars :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let x = 10
			let y = 20
			return x + y
		}
	`)
	testing.expect_value(t, val.(i64), i64(30))
}

@(test)
test_e2e_assignment :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let x = 1
			x = x + 9
			return x
		}
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

// ---- control flow ----

@(test)
test_e2e_if_true_branch :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			if 10 > 5 { return 1 }
			return 0
		}
	`)
	testing.expect_value(t, val.(i64), i64(1))
}

@(test)
test_e2e_if_false_branch :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			if 1 > 5 { return 1 }
			return 0
		}
	`)
	testing.expect_value(t, val.(i64), i64(0))
}

@(test)
test_e2e_for_loop_sum :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let total = 0
			let i = 1
			for i <= 5 {
				total = total + i
				i = i + 1
			}
			return total
		}
	`)
	testing.expect_value(t, val.(i64), i64(15))
}

// ---- functions ----

@(test)
test_e2e_function_call :: proc(t: ^testing.T) {
	val := result(`
		function add(a: int, b: int) -> int { return a + b }
		function main() { return add(3, 4) }
	`)
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_nested_calls :: proc(t: ^testing.T) {
	val := result(`
		function double(x: int) -> int { return x * 2 }
		function main() { return double(double(3)) }
	`)
	testing.expect_value(t, val.(i64), i64(12))
}

@(test)
test_e2e_recursion :: proc(t: ^testing.T) {
	val := result(`
		function factorial(n: int) -> int {
			if n <= 1 { return 1 }
			return n * factorial(n - 1)
		}
		function main() { return factorial(5) }
	`)
	testing.expect_value(t, val.(i64), i64(120))
}

// ---- c-style for ----

@(test)
test_e2e_for_c_style_sum :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let sum = 0
			for let i = 0; i < 5; i = i + 1 {
				sum = sum + i
			}
			return sum
		}
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_for_c_style_break :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let result = 0
			for let i = 0; i < 10; i = i + 1 {
				if i == 5 { break }
				result = i
			}
			return result
		}
	`)
	testing.expect_value(t, val.(i64), i64(4))
}

@(test)
test_e2e_for_c_style_i_not_visible_after :: proc(t: ^testing.T) {
	// i should not be accessible after the loop — outer x should be returned
	val := result(`
		function main() -> int {
			let x = 99
			for let i = 0; i < 3; i = i + 1 { }
			return x
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

// ---- break / continue ----

@(test)
test_e2e_break :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let i = 0
			for i < 10 {
				if i == 5 { break }
				i = i + 1
			}
			return i
		}
	`)
	testing.expect_value(t, val.(i64), i64(5))
}

@(test)
test_e2e_continue :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let sum = 0
			let i = 0
			for i < 10 {
				i = i + 1
				if i % 2 == 0 { continue }
				sum = sum + i
			}
			return sum
		}
	`)
	// sum of odd numbers 1+3+5+7+9 = 25
	testing.expect_value(t, val.(i64), i64(25))
}

@(test)
test_e2e_break_with_locals :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			let result = 0
			let i = 0
			for i < 10 {
				let x = i * 2
				if x >= 8 { break }
				result = x
				i = i + 1
			}
			return result
		}
	`)
	// last x before x>=8: x=6 (i=3), next i=4 -> x=8 -> break
	testing.expect_value(t, val.(i64), i64(6))
}

// ---- strings ----

@(test)
test_e2e_string_literal :: proc(t: ^testing.T) {
	val := result(`function main() { return "hello" }`)
	testing.expect_value(t, val.(string), "hello")
}

@(test)
test_e2e_string_eq :: proc(t: ^testing.T) {
	val := result(`function main() { return "abc" == "abc" }`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_string_neq :: proc(t: ^testing.T) {
	val := result(`function main() { return "abc" == "xyz" }`)
	testing.expect_value(t, val.(bool), false)
}

@(test)
test_e2e_string_escape_newline :: proc(t: ^testing.T) {
	val := result(`function main() { return "a\nb" }`)
	testing.expect_value(t, val.(string), "a\nb")
}

@(test)
test_e2e_string_escape_tab :: proc(t: ^testing.T) {
	val := result(`function main() { return "a\tb" }`)
	testing.expect_value(t, val.(string), "a\tb")
}

@(test)
test_e2e_string_escape_backslash :: proc(t: ^testing.T) {
	val := result(`function main() { return "a\\b" }`)
	testing.expect_value(t, val.(string), "a\\b")
}

@(test)
test_e2e_string_escape_quote :: proc(t: ^testing.T) {
	val := result(`function main() { return "say \"hi\"" }`)
	testing.expect_value(t, val.(string), "say \"hi\"")
}

@(test)
test_e2e_string_escape_in_condition :: proc(t: ^testing.T) {
	// escaped string compares equal to the decoded value
	val := result(`
		function main() -> bool {
			let s = "hello\nworld"
			return s == "hello\nworld"
		}
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_string_no_escape_fast_path :: proc(t: ^testing.T) {
	// plain string with no backslash takes the fast path
	val := result(`function main() { return "no escapes here" }`)
	testing.expect_value(t, val.(string), "no escapes here")
}

// ---- constants ----

@(test)
test_e2e_const_int :: proc(t: ^testing.T) {
	val := result(`
		const N = 42
		function main() { return N }
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_const_float :: proc(t: ^testing.T) {
	val := result(`
		const F = 3.14
		function main() { return F }
	`)
	testing.expect_value(t, val.(f64), f64(3.14))
}

@(test)
test_e2e_const_bool :: proc(t: ^testing.T) {
	val := result(`
		const FLAG = true
		function main() { return FLAG }
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_const_string :: proc(t: ^testing.T) {
	val := result(`
		const MSG = "hello"
		function main() { return MSG }
	`)
	testing.expect_value(t, val.(string), "hello")
}

@(test)
test_e2e_const_folded_add :: proc(t: ^testing.T) {
	val := result(`
		const A = 10
		const B = 20
		const C = A + B
		function main() { return C }
	`)
	testing.expect_value(t, val.(i64), i64(30))
}

@(test)
test_e2e_const_folded_arithmetic :: proc(t: ^testing.T) {
	val := result(`
		const MAX  = 100
		const HALF = MAX / 2
		const OFF  = HALF - 5
		function main() { return OFF }
	`)
	testing.expect_value(t, val.(i64), i64(45))
}

@(test)
test_e2e_const_negative :: proc(t: ^testing.T) {
	val := result(`
		const NEG = -7
		function main() { return NEG }
	`)
	testing.expect_value(t, val.(i64), i64(-7))
}

@(test)
test_e2e_const_in_loop_bound :: proc(t: ^testing.T) {
	val := result(`
		const LIMIT = 5
		function main() -> int {
			let sum = 0
			let i = 0
			for i < LIMIT {
				sum = sum + i
				i = i + 1
			}
			return sum
		}
	`)
	// 0+1+2+3+4 = 10
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_const_in_condition :: proc(t: ^testing.T) {
	val := result(`
		const THRESHOLD = 10
		function main() -> bool {
			let x = 5
			return x < THRESHOLD
		}
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_const_visible_in_function :: proc(t: ^testing.T) {
	val := result(`
		const BASE = 100
		function add_base(n: int) -> int {
			return n + BASE
		}
		function main() { return add_base(5) }
	`)
	testing.expect_value(t, val.(i64), i64(105))
}

// ---- local constants ----

@(test)
test_e2e_local_const_int :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const N = 99
			return N
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

@(test)
test_e2e_local_const_folded :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const A = 6
			const B = A * 7
			return B
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_local_const_in_loop :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const LIMIT = 5
			let sum = 0
			let i = 0
			for i < LIMIT {
				sum = sum + i
				i = i + 1
			}
			return sum
		}
	`)
	// 0+1+2+3+4 = 10
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_local_const_in_condition :: proc(t: ^testing.T) {
	val := result(`
		function main() -> bool {
			const THRESHOLD = 100
			let x = 50
			return x < THRESHOLD
		}
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_local_const_shadows_global :: proc(t: ^testing.T) {
	val := result(`
		const X = 1
		function main() -> int {
			const X = 2
			return X
		}
	`)
	testing.expect_value(t, val.(i64), i64(2))
}

@(test)
test_e2e_local_const_mixed_with_let :: proc(t: ^testing.T) {
	val := result(`
		function main() -> int {
			const STEP = 3
			let total = 0
			let i = 0
			for i < 9 {
				total = total + STEP
				i = i + STEP
			}
			return total
		}
	`)
	// 3 iterations: i=0,3,6 → total=3,6,9
	testing.expect_value(t, val.(i64), i64(9))
}

// ---- first-class functions / callbacks ----

@(test)
test_e2e_fn_passed_as_arg :: proc(t: ^testing.T) {
	val := result(`
		function double(x: int) -> int { return x * 2 }
		function apply(f: (int) -> int, x: int) -> int { return f(x) }
		function main() { return apply(double, 5) }
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_fn_stored_in_let :: proc(t: ^testing.T) {
	val := result(`
		function square(x: int) -> int { return x * x }
		function main() -> int {
			let f = square
			return f(6)
		}
	`)
	testing.expect_value(t, val.(i64), i64(36))
}

@(test)
test_e2e_fn_called_in_loop :: proc(t: ^testing.T) {
	val := result(`
		function double(x: int) -> int { return x * 2 }
		function sum_with(f: (int) -> int, n: int) -> int {
			let total = 0
			let i = 0
			for i < n {
				total += f(i)
				i += 1
			}
			return total
		}
		function main() { return sum_with(double, 5) }
	`)
	// double(0)+double(1)+double(2)+double(3)+double(4) = 0+2+4+6+8 = 20
	testing.expect_value(t, val.(i64), i64(20))
}

@(test)
test_e2e_fn_passed_to_multiple_callers :: proc(t: ^testing.T) {
	val := result(`
		function inc(x: int) -> int { return x + 1 }
		function apply(f: (int) -> int, x: int) -> int { return f(x) }
		function main() -> int {
			let a = apply(inc, 10)
			let b = apply(inc, a)
			return b
		}
	`)
	testing.expect_value(t, val.(i64), i64(12))
}

@(test)
test_e2e_two_fn_args :: proc(t: ^testing.T) {
	val := result(`
		function add(a: int, b: int) -> int { return a + b }
		function mul(a: int, b: int) -> int { return a * b }
		function combine(f: (int, int) -> int, g: (int, int) -> int, a: int, b: int) -> int {
			return f(a, b) + g(a, b)
		}
		function main() { return combine(add, mul, 3, 4) }
	`)
	// add(3,4) + mul(3,4) = 7 + 12 = 19
	testing.expect_value(t, val.(i64), i64(19))
}

@(test)
test_e2e_fn_returned_from_fn :: proc(t: ^testing.T) {
	val := result(`
		function double(x: int) -> int { return x * 2 }
		function get_fn(which: int) -> (int) -> int {
			return double
		}
		function main() -> int {
			let f = get_fn(0)
			return f(7)
		}
	`)
	testing.expect_value(t, val.(i64), i64(14))
}

// ---- input ----

@(test)
test_e2e_input_returns_string :: proc(t: ^testing.T) {
	val := result_with_stdin(`
		function main() { return input() }
	`, "hello\n")
	testing.expect_value(t, val.(string), "hello")
}

@(test)
test_e2e_input_strips_newline :: proc(t: ^testing.T) {
	val := result_with_stdin(`
		function main() { return input() }
	`, "world\n")
	testing.expect_value(t, val.(string), "world")
}

@(test)
test_e2e_input_with_prompt :: proc(t: ^testing.T) {
	// prompt is printed to stdout — just verify the return value is correct
	val := result_with_stdin(`
		function main() { return input("name: ") }
	`, "myr\n")
	testing.expect_value(t, val.(string), "myr")
}

@(test)
test_e2e_input_eq :: proc(t: ^testing.T) {
	val := result_with_stdin(`
		function main() -> bool {
			let s = input()
			return s == "yes"
		}
	`, "yes\n")
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_input_multiple :: proc(t: ^testing.T) {
	// second input call reads the next line
	val := result_with_stdin(`
		function main() -> int {
			let a = input()
			let b = input()
			let ok = 0
			if a == "foo" { ok = ok + 1 }
			if b == "bar" { ok = ok + 1 }
			return ok
		}
	`, "foo\nbar\n")
	testing.expect_value(t, val.(i64), i64(2))
}

// ---- runtime errors ----

@(test)
test_e2e_division_by_zero :: proc(t: ^testing.T) {
	_, err := run_source("function main() { return 1 / 0 }")
	testing.expect_value(t, err, Maybe(VMError)(.DIVISION_BY_ZERO))
}

// ---- bit shift ----

@(test)
test_e2e_shl_basic :: proc(t: ^testing.T) {
	val := result("function main() { return 1 << 3 }")
	testing.expect_value(t, val.(i64), i64(8))
}

@(test)
test_e2e_shr_basic :: proc(t: ^testing.T) {
	val := result("function main() { return 16 >> 2 }")
	testing.expect_value(t, val.(i64), i64(4))
}

@(test)
test_e2e_shl_zero :: proc(t: ^testing.T) {
	val := result("function main() { return 5 << 0 }")
	testing.expect_value(t, val.(i64), i64(5))
}

@(test)
test_e2e_shr_to_zero :: proc(t: ^testing.T) {
	val := result("function main() { return 1 >> 1 }")
	testing.expect_value(t, val.(i64), i64(0))
}

@(test)
test_e2e_shl_precedence_add :: proc(t: ^testing.T) {
	// + binds tighter: (1 + 2) << 1 = 6, not 1 + (2 << 1) = 5
	val := result("function main() { return 1 + 2 << 1 }")
	testing.expect_value(t, val.(i64), i64(6))
}

@(test)
test_e2e_shr_precedence_mul :: proc(t: ^testing.T) {
	// * binds tighter: 8 >> (1 * 2) = 2
	val := result("function main() { return 8 >> 1 * 2 }")
	testing.expect_value(t, val.(i64), i64(2))
}

@(test)
test_e2e_shl_variable :: proc(t: ^testing.T) {
	val := result(`function main() {
		let n = 4
		return n << 2
	}`)
	testing.expect_value(t, val.(i64), i64(16))
}

@(test)
test_e2e_shr_variable :: proc(t: ^testing.T) {
	val := result(`function main() {
		let n = 64
		return n >> 3
	}`)
	testing.expect_value(t, val.(i64), i64(8))
}

@(test)
test_e2e_shift_in_loop :: proc(t: ^testing.T) {
	// sum powers of 2: 1+2+4+8+16 = 31
	val := result(`function main() {
		let sum = 0
		let i = 0
		for i < 5 {
			sum += 1 << i
			i += 1
		}
		return sum
	}`)
	testing.expect_value(t, val.(i64), i64(31))
}

@(test)
test_e2e_shift_comparison :: proc(t: ^testing.T) {
	// shift has lower precedence than comparison? No — shift > comparison
	// (8 >> 1) > 3  =  4 > 3  = true
	val := result("function main() { return 8 >> 1 > 3 }")
	testing.expect_value(t, val.(bool), true)
}

// ---- structs ----

@(test)
test_e2e_struct_field_read :: proc(t: ^testing.T) {
	val := result(`
		struct Point { x: float, y: float }
		function main() {
			let p = Point{x = 3.0, y = 4.0}
			return p.x
		}
	`)
	testing.expect_value(t, val.(f64), f64(3))
}

@(test)
test_e2e_struct_second_field_read :: proc(t: ^testing.T) {
	val := result(`
		struct Point { x: float, y: float }
		function main() {
			let p = Point{x = 3.0, y = 4.0}
			return p.y
		}
	`)
	testing.expect_value(t, val.(f64), f64(4))
}

@(test)
test_e2e_struct_field_write :: proc(t: ^testing.T) {
	val := result(`
		struct Point { x: float, y: float }
		function main() {
			let p = Point{x = 1.0, y = 2.0}
			p.x = 99.0
			return p.x
		}
	`)
	testing.expect_value(t, val.(f64), f64(99))
}

@(test)
test_e2e_struct_value_semantics :: proc(t: ^testing.T) {
	// let q = p copies — mutating q must not affect p
	val := result(`
		struct Point { x: float, y: float }
		function main() {
			let p = Point{x = 1.0, y = 2.0}
			let q = p
			q.x = 99.0
			return p.x
		}
	`)
	testing.expect_value(t, val.(f64), f64(1))
}

@(test)
test_e2e_struct_reassign :: proc(t: ^testing.T) {
	// overwriting an existing struct local
	val := result(`
		struct Point { x: float, y: float }
		function main() {
			let p = Point{x = 1.0, y = 2.0}
			let q = Point{x = 10.0, y = 20.0}
			p = q
			return p.x
		}
	`)
	testing.expect_value(t, val.(f64), f64(10))
}

@(test)
test_e2e_struct_scalar_neighbour :: proc(t: ^testing.T) {
	// a scalar local after a struct must land at the correct slot
	val := result(`
		struct Point { x: float, y: float }
		function main() {
			let p = Point{x = 1.0, y = 2.0}
			let n = 42
			return n
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_struct_in_loop :: proc(t: ^testing.T) {
	// struct created and destroyed each iteration — scope cleanup must be correct
	val := result(`
		struct Point { x: float, y: float }
		function main() {
			let sum = 0.0
			for let i = 0; i < 3; i = i + 1 {
				let p = Point{x = 1.0, y = 2.0}
				sum = sum + p.x
			}
			return sum
		}
	`)
	testing.expect_value(t, val.(f64), f64(3))
}

@(test)
test_e2e_struct_nested_read :: proc(t: ^testing.T) {
	val := result(`
		struct Vec2 { x: float, y: float }
		struct Rect { origin: Vec2, size: Vec2 }
		function main() {
			let r = Rect{origin = Vec2{x = 1.0, y = 2.0}, size = Vec2{x = 10.0, y = 20.0}}
			return r.origin.y
		}
	`)
	testing.expect_value(t, val.(f64), f64(2))
}

@(test)
test_e2e_struct_nested_second_field :: proc(t: ^testing.T) {
	val := result(`
		struct Vec2 { x: float, y: float }
		struct Rect { origin: Vec2, size: Vec2 }
		function main() {
			let r = Rect{origin = Vec2{x = 1.0, y = 2.0}, size = Vec2{x = 10.0, y = 20.0}}
			return r.size.y
		}
	`)
	testing.expect_value(t, val.(f64), f64(20))
}

@(test)
test_e2e_struct_nested_write :: proc(t: ^testing.T) {
	val := result(`
		struct Vec2 { x: float, y: float }
		struct Rect { origin: Vec2, size: Vec2 }
		function main() {
			let r = Rect{origin = Vec2{x = 1.0, y = 2.0}, size = Vec2{x = 10.0, y = 20.0}}
			r.size.x = 42.0
			return r.size.x
		}
	`)
	testing.expect_value(t, val.(f64), f64(42))
}

@(test)
test_e2e_struct_nested_value_semantics :: proc(t: ^testing.T) {
	// let q = r is a full copy — mutating q.origin.x must not affect r.origin.x
	val := result(`
		struct Vec2 { x: float, y: float }
		struct Rect { origin: Vec2, size: Vec2 }
		function main() {
			let r = Rect{origin = Vec2{x = 5.0, y = 6.0}, size = Vec2{x = 10.0, y = 20.0}}
			let q = r
			q.origin.x = 0.0
			return r.origin.x
		}
	`)
	testing.expect_value(t, val.(f64), f64(5))
}

@(test)
test_e2e_struct_int_fields :: proc(t: ^testing.T) {
	val := result(`
		struct Counter { value: int, step: int }
		function main() {
			let c = Counter{value = 0, step = 5}
			c.value = c.value + c.step
			return c.value
		}
	`)
	testing.expect_value(t, val.(i64), i64(5))
}

// ---- pointers ----

@(test)
test_e2e_ptr_field_read :: proc(t: ^testing.T) {
	val := result(`
		struct Point { x: i64, y: i64 }
		function main() -> i64 {
			let p: ^Point = new Point{x = 10, y = 20}
			return p.x
		}
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_ptr_second_field_read :: proc(t: ^testing.T) {
	val := result(`
		struct Point { x: i64, y: i64 }
		function main() -> i64 {
			let p: ^Point = new Point{x = 10, y = 20}
			return p.y
		}
	`)
	testing.expect_value(t, val.(i64), i64(20))
}

@(test)
test_e2e_ptr_field_write :: proc(t: ^testing.T) {
	val := result(`
		struct Point { x: i64, y: i64 }
		function main() -> i64 {
			let p: ^Point = new Point{x = 10, y = 20}
			p.x = 99
			return p.x
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

@(test)
test_e2e_ptr_compound_assign :: proc(t: ^testing.T) {
	val := result(`
		struct Point { x: i64, y: i64 }
		function main() -> i64 {
			let p: ^Point = new Point{x = 10, y = 20}
			p.x += 5
			return p.x
		}
	`)
	testing.expect_value(t, val.(i64), i64(15))
}

@(test)
test_e2e_ptr_as_fn_param :: proc(t: ^testing.T) {
	// function takes ^Point and mutates it; caller sees the change
	val := result(`
		struct Point { x: i64, y: i64 }
		function scale(p: ^Point, factor: i64) {
			p.x *= factor
			p.y *= factor
		}
		function main() -> i64 {
			let p: ^Point = new Point{x = 3, y = 4}
			scale(p, 10)
			return p.x
		}
	`)
	testing.expect_value(t, val.(i64), i64(30))
}

@(test)
test_e2e_ptr_fn_return_annotated :: proc(t: ^testing.T) {
	val := result(`
		struct Point { x: i64, y: i64 }
		function make_point(x: i64, y: i64) -> ^Point {
			return new Point{x = x, y = y}
		}
		function main() -> i64 {
			let p: ^Point = make_point(7, 8)
			return p.y
		}
	`)
	testing.expect_value(t, val.(i64), i64(8))
}

@(test)
test_e2e_ptr_fn_return_inferred :: proc(t: ^testing.T) {
	// no type annotation on let — ptr_inner inferred from call return type
	val := result(`
		struct Point { x: i64, y: i64 }
		function make_point(x: i64, y: i64) -> ^Point {
			return new Point{x = x, y = y}
		}
		function main() -> i64 {
			let p = make_point(7, 8)
			return p.x
		}
	`)
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_ptr_explicit_deref :: proc(t: ^testing.T) {
	// p^ copies the struct; returned field is from the copy
	val := result(`
		struct Point { x: i64, y: i64 }
		function deref_copy(p: ^Point) -> Point { return p^ }
		function main() -> i64 {
			let p: ^Point = new Point{x = 42, y = 0}
			let copy = deref_copy(p)
			return copy.x
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_ptr_deref_isolation :: proc(t: ^testing.T) {
	// mutating the deref'd copy must not affect the original pointer
	val := result(`
		struct Point { x: i64, y: i64 }
		function deref_copy(p: ^Point) -> Point { return p^ }
		function main() -> i64 {
			let p: ^Point = new Point{x = 1, y = 2}
			let copy = deref_copy(p)
			copy.x = 999
			return p.x
		}
	`)
	testing.expect_value(t, val.(i64), i64(1))
}

@(test)
test_e2e_ptr_nested_field_read :: proc(t: ^testing.T) {
	val := result(`
		struct Vec2 { x: i64, y: i64 }
		struct Rect  { origin: Vec2, size: Vec2 }
		function make_rect(ox: i64, oy: i64, sw: i64, sh: i64) -> ^Rect {
			return new Rect{origin = Vec2{x = ox, y = oy}, size = Vec2{x = sw, y = sh}}
		}
		function main() -> i64 {
			let r = make_rect(1, 2, 10, 5)
			return r.origin.x
		}
	`)
	testing.expect_value(t, val.(i64), i64(1))
}

@(test)
test_e2e_ptr_nested_second_field :: proc(t: ^testing.T) {
	val := result(`
		struct Vec2 { x: i64, y: i64 }
		struct Rect  { origin: Vec2, size: Vec2 }
		function make_rect(ox: i64, oy: i64, sw: i64, sh: i64) -> ^Rect {
			return new Rect{origin = Vec2{x = ox, y = oy}, size = Vec2{x = sw, y = sh}}
		}
		function main() -> i64 {
			let r = make_rect(1, 2, 10, 5)
			return r.size.y
		}
	`)
	testing.expect_value(t, val.(i64), i64(5))
}

@(test)
test_e2e_ptr_nested_field_write :: proc(t: ^testing.T) {
	val := result(`
		struct Vec2 { x: i64, y: i64 }
		struct Rect  { origin: Vec2, size: Vec2 }
		function make_rect(ox: i64, oy: i64, sw: i64, sh: i64) -> ^Rect {
			return new Rect{origin = Vec2{x = ox, y = oy}, size = Vec2{x = sw, y = sh}}
		}
		function main() -> i64 {
			let r = make_rect(1, 2, 10, 5)
			r.size.x = 42
			return r.size.x
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_ptr_nested_compound_assign :: proc(t: ^testing.T) {
	val := result(`
		struct Vec2 { x: i64, y: i64 }
		struct Rect  { origin: Vec2, size: Vec2 }
		function make_rect(ox: i64, oy: i64, sw: i64, sh: i64) -> ^Rect {
			return new Rect{origin = Vec2{x = ox, y = oy}, size = Vec2{x = sw, y = sh}}
		}
		function area(r: ^Rect) -> i64 { return r.size.x * r.size.y }
		function main() -> i64 {
			let r = make_rect(1, 2, 10, 5)
			r.size.x *= 3
			r.size.y *= 3
			return area(r)
		}
	`)
	// (10*3) * (5*3) = 30 * 15 = 450
	testing.expect_value(t, val.(i64), i64(450))
}

@(test)
test_e2e_ptr_xor_not_deref :: proc(t: ^testing.T) {
	// ^ in infix position is XOR, not deref
	val := result(`
		function main() -> i64 {
			let a = 3
			let b = 5
			return a ^ b
		}
	`)
	testing.expect_value(t, val.(i64), i64(6))
}

@(test)
test_e2e_ptr_write_then_read_across_fn :: proc(t: ^testing.T) {
	// write through pointer in one fn, read through same pointer in another
	val := result(`
		struct Counter { n: i64 }
		function inc(c: ^Counter) { c.n += 1 }
		function get(c: ^Counter) -> i64 { return c.n }
		function main() -> i64 {
			let c: ^Counter = new Counter{n = 0}
			inc(c)
			inc(c)
			inc(c)
			return get(c)
		}
	`)
	testing.expect_value(t, val.(i64), i64(3))
}

// ---- nil pointers ----

@(test)
test_e2e_ptr_nil_field_init :: proc(t: ^testing.T) {
	// nil is assignable to a ^T field
	val := result(`
		struct Node { val: i64, next: ^Node }
		function main() -> i64 {
			let n: ^Node = new Node{val = 42, next = nil}
			return n.val
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_ptr_nil_eq :: proc(t: ^testing.T) {
	// freshly allocated pointer is not nil
	val := result(`
		struct Node { val: i64, next: ^Node }
		function main() -> bool {
			let n: ^Node = new Node{val = 1, next = nil}
			return n == nil
		}
	`)
	testing.expect_value(t, val.(bool), false)
}

@(test)
test_e2e_ptr_nil_neq :: proc(t: ^testing.T) {
	val := result(`
		struct Node { val: i64, next: ^Node }
		function main() -> bool {
			let n: ^Node = new Node{val = 1, next = nil}
			return n != nil
		}
	`)
	testing.expect_value(t, val.(bool), true)
}

@(test)
test_e2e_ptr_nil_field_neq :: proc(t: ^testing.T) {
	// the nil field itself compares equal to nil
	val := result(`
		struct Node { val: i64, next: ^Node }
		function main() -> bool {
			let n: ^Node = new Node{val = 1, next = nil}
			return n.next == nil
		}
	`)
	testing.expect_value(t, val.(bool), true)
}

// ---- recursive (self-referential) struct ----

@(test)
test_e2e_recursive_struct_two_nodes :: proc(t: ^testing.T) {
	val := result(`
		struct Node { val: i64, next: ^Node }
		function main() -> i64 {
			let b: ^Node = new Node{val = 2, next = nil}
			let a: ^Node = new Node{val = 1, next = b}
			return a.next.val
		}
	`)
	testing.expect_value(t, val.(i64), i64(2))
}

@(test)
test_e2e_recursive_struct_chain_sum :: proc(t: ^testing.T) {
	val := result(`
		struct Node { val: i64, next: ^Node }
		function main() -> i64 {
			let c: ^Node = new Node{val = 3, next = nil}
			let b: ^Node = new Node{val = 2, next = c}
			let a: ^Node = new Node{val = 1, next = b}
			let sum = 0
			let cur = a
			for cur != nil {
				sum += cur.val
				cur = cur.next
			}
			return sum
		}
	`)
	testing.expect_value(t, val.(i64), i64(6))
}

@(test)
test_e2e_recursive_struct_prepend_loop :: proc(t: ^testing.T) {
	// build a list by prepending in a loop, verify sum
	val := result(`
		struct Node { val: i64, next: ^Node }
		function main() -> i64 {
			let head: ^Node = new Node{val = 5, next = nil}
			for let i = 4; i >= 1; i -= 1 {
				head = new Node{val = i, next = head}
			}
			let sum = 0
			let cur = head
			for cur != nil {
				sum += cur.val
				cur = cur.next
			}
			return sum
		}
	`)
	// 1+2+3+4+5 = 15
	testing.expect_value(t, val.(i64), i64(15))
}

@(test)
test_e2e_recursive_struct_fn_traverse :: proc(t: ^testing.T) {
	val := result(`
		struct Node { val: i64, next: ^Node }
		function sum_list(n: ^Node) -> i64 {
			let total = 0
			for n != nil {
				total += n.val
				n = n.next
			}
			return total
		}
		function main() -> i64 {
			let c: ^Node = new Node{val = 3, next = nil}
			let b: ^Node = new Node{val = 2, next = c}
			let a: ^Node = new Node{val = 1, next = b}
			return sum_list(a)
		}
	`)
	testing.expect_value(t, val.(i64), i64(6))
}

// ---- enums ----

@(test)
test_e2e_enum_unit_variant :: proc(t: ^testing.T) {
	val := result(`
		enum Color { Red {}, Green {}, Blue {} }
		function main() -> i64 {
			let c = Color.Red {}
			return 1
		}
	`)
	testing.expect_value(t, val.(i64), i64(1))
}

@(test)
test_e2e_enum_variant_with_fields :: proc(t: ^testing.T) {
	val := result(`
		enum Shape { Circle { radius: float }, Rect { w: float, h: float } }
		function main() -> float {
			let s = Shape.Circle { radius = 3.0 }
			return 1.0
		}
	`)
	testing.expect_value(t, val.(f64), f64(1.0))
}

@(test)
test_e2e_enum_passed_to_function :: proc(t: ^testing.T) {
	val := result(`
		enum Shape { Circle { radius: float }, Rect { w: float, h: float } }
		function describe(s: Shape) -> i64 { return 42 }
		function main() -> i64 {
			let s = Shape.Rect { w = 10.0, h = 5.0 }
			return describe(s)
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_enum_returned_from_function :: proc(t: ^testing.T) {
	val := result(`
		enum Shape { Circle { radius: float } }
		function make_circle(r: float) -> Shape { return Shape.Circle { radius = r } }
		function main() -> i64 {
			let s = make_circle(5.0)
			return 99
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

@(test)
test_e2e_enum_multiple_variants_same_enum :: proc(t: ^testing.T) {
	val := result(`
		enum Msg { Ok { code: i64 }, Err { code: i64 } }
		function main() -> i64 {
			let a = Msg.Ok  { code = 1 }
			let b = Msg.Err { code = 2 }
			return 7
		}
	`)
	testing.expect_value(t, val.(i64), i64(7))
}

// ---- enums: additional runtime tests ----

@(test)
test_e2e_enum_int_field :: proc(t: ^testing.T) {
	val := result(`
		enum Msg { Ok { code: i64 }, Err { code: i64 } }
		function main() -> i64 {
			let m = Msg.Ok { code = 42 }
			return 1
		}
	`)
	testing.expect_value(t, val.(i64), i64(1))
}

@(test)
test_e2e_enum_string_field :: proc(t: ^testing.T) {
	val := result(`
		enum Event { Click { label: str } }
		function main() -> i64 {
			let e = Event.Click { label = "submit" }
			return 1
		}
	`)
	testing.expect_value(t, val.(i64), i64(1))
}

@(test)
test_e2e_enum_annotated_let :: proc(t: ^testing.T) {
	// explicit type annotation on the let binding
	val := result(`
		enum Shape { Circle { radius: float } }
		function main() -> i64 {
			let s: Shape = Shape.Circle { radius = 3.14 }
			return 1
		}
	`)
	testing.expect_value(t, val.(i64), i64(1))
}

@(test)
test_e2e_enum_in_loop :: proc(t: ^testing.T) {
	// construct enum values inside a loop; each iteration allocates a new value
	val := result(`
		enum Counter { Step { n: i64 } }
		function main() -> i64 {
			let sum = 0
			for let i = 1; i <= 5; i += 1 {
				let s = Counter.Step { n = i }
				sum += i
			}
			return sum
		}
	`)
	testing.expect_value(t, val.(i64), i64(15))
}

@(test)
test_e2e_enum_as_expression_stmt :: proc(t: ^testing.T) {
	// enum literal used as an expression statement — value must be popped correctly
	val := result(`
		enum Shape { Circle { radius: float } }
		function main() -> i64 {
			Shape.Circle { radius = 1.0 }
			Shape.Circle { radius = 2.0 }
			return 7
		}
	`)
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_enum_two_enums :: proc(t: ^testing.T) {
	// two independent enum types coexist
	val := result(`
		enum Color  { Red {}, Blue {} }
		enum Shape  { Circle { r: float }, Rect { w: float, h: float } }
		function main() -> i64 {
			let c = Color.Red {}
			let s = Shape.Rect { w = 4.0, h = 3.0 }
			return 1
		}
	`)
	testing.expect_value(t, val.(i64), i64(1))
}

@(test)
test_e2e_enum_variant_forwarded_through_call :: proc(t: ^testing.T) {
	// construct in callee, return to caller, use in another call
	val := result(`
		enum Wrap { Val { x: i64 } }
		function make(n: i64) -> Wrap { return Wrap.Val { x = n } }
		function consume(w: Wrap)     -> i64  { return 99 }
		function main() -> i64 {
			return consume(make(5))
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

// ---- enums: stack-layout runtime correctness ----
// run_source returns the TOP stack slot. When main returns an N-slot enum value,
// __main__'s RETURN 1 keeps only the top slot, which is the last field (or nil
// for padding). These tests exploit that to verify actual field values survive
// construction, function calls, copies, and reassignment.

@(test)
test_e2e_enum_field_survives_return :: proc(t: ^testing.T) {
	// Single-variant 1-field enum: slots = [disc=0, x]. Stack top after __main__ RETURN 1 = x.
	val := result(`
		enum Val { Only { x: i64 } }
		function main() -> Val { return Val.Only { x = 55 } }
	`)
	testing.expect_value(t, val.(i64), i64(55))
}

@(test)
test_e2e_enum_two_field_variant_top_slot :: proc(t: ^testing.T) {
	// Two-field variant is the widest — no padding. Rect { w, h } → slots [disc=1, w, h].
	// Stack top = h after __main__ RETURN 1.
	val := result(`
		enum Shape { Circle { radius: float }, Rect { w: float, h: float } }
		function main() -> Shape { return Shape.Rect { w = 7.0, h = 99.0 } }
	`)
	testing.expect_value(t, val.(f64), f64(99.0))
}

@(test)
test_e2e_enum_scalar_after_enum_local :: proc(t: ^testing.T) {
	// Scalar local declared after a 3-slot enum must land at the correct stack slot.
	val := result(`
		enum Shape { Circle { radius: float }, Rect { w: float, h: float } }
		function main() -> i64 {
			let s = Shape.Circle { radius = 5.0 }
			let n = 42
			return n
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_enum_scalar_param_after_enum_param :: proc(t: ^testing.T) {
	// Second (scalar) parameter must be readable at its correct slot when the first
	// parameter is a multi-slot enum.
	val := result(`
		enum Shape { Circle { radius: float }, Rect { w: float, h: float } }
		function tag(s: Shape, n: i64) -> i64 { return n }
		function main() -> i64 {
			return tag(Shape.Circle { radius = 5.0 }, 77)
		}
	`)
	testing.expect_value(t, val.(i64), i64(77))
}

@(test)
test_e2e_enum_copy_scalar_after :: proc(t: ^testing.T) {
	// let b = a copies all slots of the enum; a scalar declared after both must not
	// be corrupted.
	val := result(`
		enum Shape { Circle { radius: float }, Rect { w: float, h: float } }
		function main() -> i64 {
			let a = Shape.Circle { radius = 5.0 }
			let b = a
			let n = 99
			return n
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

@(test)
test_e2e_enum_expression_stmt_pops_all :: proc(t: ^testing.T) {
	// An enum literal used as an expression statement must pop all of its slots.
	// If only 1 slot is popped instead of 3, the next local lands at the wrong position.
	val := result(`
		enum Shape { Circle { radius: float }, Rect { w: float, h: float } }
		function main() -> i64 {
			Shape.Circle { radius = 1.0 }
			let n = 55
			return n
		}
	`)
	testing.expect_value(t, val.(i64), i64(55))
}

@(test)
test_e2e_enum_reassign_scalar_after :: proc(t: ^testing.T) {
	// Overwriting an enum local must not corrupt a scalar neighbour declared after it.
	val := result(`
		enum Shape { Circle { radius: float }, Rect { w: float, h: float } }
		function main() -> i64 {
			let s = Shape.Circle { radius = 1.0 }
			let n = 33
			s = Shape.Rect { w = 2.0, h = 4.0 }
			return n
		}
	`)
	testing.expect_value(t, val.(i64), i64(33))
}

@(test)
test_e2e_enum_identity_function :: proc(t: ^testing.T) {
	// Enum passed to identity function and returned; field value must survive
	// the full call + return round trip.
	val := result(`
		enum Val { Only { x: i64 } }
		function identity(v: Val) -> Val { return v }
		function main() -> Val { return identity(Val.Only { x = 88 }) }
	`)
	testing.expect_value(t, val.(i64), i64(88))
}

// ---- match expression ----

@(test)
test_e2e_match_first_arm :: proc(t: ^testing.T) {
	// Subject matches the first arm; binding is readable in body.
	val := result(`
		enum Shape { Circle { radius: i64 }, Rect { w: i64, h: i64 } }
		function main() -> i64 {
			let s = Shape.Circle { radius = 42 }
			match s {
				Shape.Circle { radius } => { return radius }
				Shape.Rect { w, h } => { return 0 }
			}
			return -1
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_e2e_match_second_arm :: proc(t: ^testing.T) {
	// Subject matches the second arm; second field is returned.
	val := result(`
		enum Shape { Circle { radius: i64 }, Rect { w: i64, h: i64 } }
		function main() -> i64 {
			let s = Shape.Rect { w = 10, h = 20 }
			match s {
				Shape.Circle { radius } => { return 0 }
				Shape.Rect { w, h } => { return h }
			}
			return -1
		}
	`)
	testing.expect_value(t, val.(i64), i64(20))
}

@(test)
test_e2e_match_two_bindings :: proc(t: ^testing.T) {
	// Both field bindings are accessible and can be used together.
	val := result(`
		enum Shape { Circle { radius: i64 }, Rect { w: i64, h: i64 } }
		function main() -> i64 {
			let s = Shape.Rect { w = 3, h = 7 }
			match s {
				Shape.Circle { radius } => { return 0 }
				Shape.Rect { w, h } => { return w + h }
			}
			return -1
		}
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_match_after_reassign :: proc(t: ^testing.T) {
	// Reassigning the enum variable before match: correct arm fires on new value.
	val := result(`
		enum Shape { Circle { radius: i64 }, Rect { w: i64, h: i64 } }
		function main() -> i64 {
			let s = Shape.Circle { radius = 5 }
			s = Shape.Rect { w = 3, h = 9 }
			match s {
				Shape.Circle { radius } => { return 0 }
				Shape.Rect { w, h } => { return h }
			}
			return -1
		}
	`)
	testing.expect_value(t, val.(i64), i64(9))
}

@(test)
test_e2e_match_as_stmt_scalar_after :: proc(t: ^testing.T) {
	// match used as a statement; scalar local declared after it must land correctly.
	val := result(`
		enum Shape { Circle { radius: i64 }, Rect { w: i64, h: i64 } }
		function main() -> i64 {
			let s = Shape.Circle { radius = 5 }
			match s {
				Shape.Circle { radius } => { return radius }
				Shape.Rect { w, h } => { return 0 }
			}
			return -1
		}
	`)
	testing.expect_value(t, val.(i64), i64(5))
}

@(test)
test_e2e_match_via_function_param :: proc(t: ^testing.T) {
	// match inside a function that receives the enum as a parameter.
	val := result(`
		enum Msg { Ok { code: i64 }, Err { code: i64 } }
		function handle(m: Msg) -> i64 {
			match m {
				Msg.Ok { code } => { return code }
				Msg.Err { code } => { return 0 - code }
			}
			return 0
		}
		function main() -> i64 {
			return handle(Msg.Ok { code = 77 })
		}
	`)
	testing.expect_value(t, val.(i64), i64(77))
}

// ---- match: wildcard arm ----

@(test)
test_e2e_match_wildcard_catches_unmatched :: proc(t: ^testing.T) {
	// Wildcard arm fires when no enum arm matches.
	val := result(`
		enum Shape { Circle { radius: i64 }, Rect { w: i64, h: i64 } }
		function main() -> i64 {
			let s = Shape.Rect { w = 3, h = 7 }
			match s {
				Shape.Circle { radius } => { return radius }
				_ => { return 99 }
			}
			return 0
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

@(test)
test_e2e_match_wildcard_not_reached_when_arm_matches :: proc(t: ^testing.T) {
	// Wildcard is skipped when an earlier arm already matched.
	val := result(`
		enum Shape { Circle { radius: i64 }, Rect { w: i64, h: i64 } }
		function main() -> i64 {
			let s = Shape.Circle { radius = 5 }
			match s {
				Shape.Circle { radius } => { return radius }
				_ => { return 99 }
			}
			return 0
		}
	`)
	testing.expect_value(t, val.(i64), i64(5))
}

// ---- match: scalar subject ----

@(test)
test_e2e_match_scalar_first_arm :: proc(t: ^testing.T) {
	// Scalar match: first literal arm fires.
	val := result(`
		function main() -> i64 {
			let x: i64 = 0
			match x {
				0 => { return 100 }
				1 => { return 200 }
				_ => { return 0 }
			}
			return -1
		}
	`)
	testing.expect_value(t, val.(i64), i64(100))
}

@(test)
test_e2e_match_scalar_second_arm :: proc(t: ^testing.T) {
	// Scalar match: second literal arm fires.
	val := result(`
		function main() -> i64 {
			let x: i64 = 1
			match x {
				0 => { return 100 }
				1 => { return 200 }
				_ => { return 0 }
			}
			return -1
		}
	`)
	testing.expect_value(t, val.(i64), i64(200))
}

@(test)
test_e2e_match_scalar_wildcard :: proc(t: ^testing.T) {
	// Scalar match: wildcard fires when no literal matches.
	val := result(`
		function main() -> i64 {
			let x: i64 = 42
			match x {
				0 => { return 100 }
				1 => { return 200 }
				_ => { return 777 }
			}
			return -1
		}
	`)
	testing.expect_value(t, val.(i64), i64(777))
}

// ---- match: exhaustiveness ----

@(test)
test_e2e_match_non_exhaustive_rejected :: proc(t: ^testing.T) {
	// Missing Rect arm — type checker should report an error.
	n := typecheck_error_count(`
		enum Shape { Circle { radius: i64 }, Rect { w: i64, h: i64 } }
		function main() {
			let s = Shape.Circle { radius = 1 }
			match s {
				Shape.Circle { radius } => { }
			}
		}
	`)
	testing.expect(t, n > 0, "expected exhaustiveness error: Rect not covered")
}

@(test)
test_e2e_match_wildcard_makes_exhaustive :: proc(t: ^testing.T) {
	// Wildcard arm satisfies exhaustiveness even if enum arms are missing.
	n := typecheck_error_count(`
		enum Shape { Circle { radius: i64 }, Rect { w: i64, h: i64 } }
		function main() {
			let s = Shape.Circle { radius = 1 }
			match s {
				Shape.Circle { radius } => { }
				_ => { }
			}
		}
	`)
	testing.expect(t, n == 0, "wildcard should satisfy exhaustiveness check")
}

// ---- match: expression result ----

@(test)
test_e2e_match_as_expression :: proc(t: ^testing.T) {
	// match used as an expression assigned to a let binding.
	val := result(`
		function main() -> i64 {
			let x: i64 = 7
			let y = match x {
				7 => 42
				_ => 0
			}
			return y
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

// ---- enums: type-error rejection ----

@(test)
test_e2e_enum_type_error_wrong_field_type :: proc(t: ^testing.T) {
	n := typecheck_error_count(`
		enum Shape { Circle { radius: float } }
		function main() { let s = Shape.Circle { radius = "oops" } }
	`)
	testing.expect(t, n > 0, "expected type error: string where float required")
}

@(test)
test_e2e_enum_type_error_unknown_variant :: proc(t: ^testing.T) {
	n := typecheck_error_count(`
		enum Shape { Circle { radius: float } }
		function main() { let s = Shape.Triangle { radius = 1.0 } }
	`)
	testing.expect(t, n > 0, "expected type error: unknown variant 'Triangle'")
}

@(test)
test_e2e_enum_type_error_unknown_field :: proc(t: ^testing.T) {
	n := typecheck_error_count(`
		enum Shape { Circle { radius: float } }
		function main() { let s = Shape.Circle { bogus = 1.0 } }
	`)
	testing.expect(t, n > 0, "expected type error: unknown field 'bogus'")
}

@(test)
test_e2e_enum_type_error_undefined_enum :: proc(t: ^testing.T) {
	n := typecheck_error_count(`
		function main() { let s = NoSuchEnum.Variant { x = 1 } }
	`)
	testing.expect(t, n > 0, "expected type error: undefined enum")
}

@(test)
test_e2e_enum_wrong_arg_type :: proc(t: ^testing.T) {
	// passing a Shape where i64 is expected
	n := typecheck_error_count(`
		enum Shape { Circle { r: float } }
		function add(a: i64, b: i64) -> i64 { return a + b }
		function main() { add(Shape.Circle { r = 1.0 }, 2) }
	`)
	testing.expect(t, n > 0, "expected type error: enum where i64 required")
}

// ---- generics ----

@(test)
test_e2e_generic_max_int :: proc(t: ^testing.T) {
	val := result(`
		function max[T](a: T, b: T) -> T {
			if a > b { return a }
			return b
		}
		function main() -> i64 { return max(3, 7) }
	`)
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_generic_max_float :: proc(t: ^testing.T) {
	val := result(`
		function max[T](a: T, b: T) -> T {
			if a > b { return a }
			return b
		}
		function main() -> float { return max(3.14, 2.71) }
	`)
	testing.expect_value(t, val.(f64), f64(3.14))
}

@(test)
test_e2e_generic_min_int :: proc(t: ^testing.T) {
	val := result(`
		function min[T](a: T, b: T) -> T {
			if a < b { return a }
			return b
		}
		function main() -> i64 { return min(10, 3) }
	`)
	testing.expect_value(t, val.(i64), i64(3))
}

@(test)
test_e2e_generic_add :: proc(t: ^testing.T) {
	val := result(`
		function add[T](a: T, b: T) -> T { return a + b }
		function main() -> i64 { return add(3, 4) }
	`)
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_generic_add_float :: proc(t: ^testing.T) {
	val := result(`
		function add[T](a: T, b: T) -> T { return a + b }
		function main() -> float { return add(1.5, 2.5) }
	`)
	testing.expect_value(t, val.(f64), f64(4.0))
}

@(test)
test_e2e_generic_two_instantiations :: proc(t: ^testing.T) {
	// Same template instantiated at both int and float in the same program.
	val := result(`
		function max[T](a: T, b: T) -> T {
			if a > b { return a }
			return b
		}
		function main() -> i64 {
			let a = max(3, 7)
			let b = max(1.5, 2.5)
			return a
		}
	`)
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_generic_nested_clamp_hi :: proc(t: ^testing.T) {
	// clamp calls max and min internally — nested generic instantiation.
	val := result(`
		function max[T](a: T, b: T) -> T {
			if a > b { return a }
			return b
		}
		function min[T](a: T, b: T) -> T {
			if a < b { return a }
			return b
		}
		function clamp[T](val: T, lo: T, hi: T) -> T {
			return max(min(val, hi), lo)
		}
		function main() -> i64 { return clamp(15, 0, 10) }
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_generic_nested_clamp_lo :: proc(t: ^testing.T) {
	val := result(`
		function max[T](a: T, b: T) -> T {
			if a > b { return a }
			return b
		}
		function min[T](a: T, b: T) -> T {
			if a < b { return a }
			return b
		}
		function clamp[T](val: T, lo: T, hi: T) -> T {
			return max(min(val, hi), lo)
		}
		function main() -> i64 { return clamp(-5, 0, 10) }
	`)
	testing.expect_value(t, val.(i64), i64(0))
}

@(test)
test_e2e_generic_nested_clamp_mid :: proc(t: ^testing.T) {
	// Value within range passes through unchanged.
	val := result(`
		function max[T](a: T, b: T) -> T {
			if a > b { return a }
			return b
		}
		function min[T](a: T, b: T) -> T {
			if a < b { return a }
			return b
		}
		function clamp[T](val: T, lo: T, hi: T) -> T {
			return max(min(val, hi), lo)
		}
		function main() -> i64 { return clamp(5, 0, 10) }
	`)
	testing.expect_value(t, val.(i64), i64(5))
}

@(test)
test_e2e_generic_called_multiple_times :: proc(t: ^testing.T) {
	// Same instantiation called more than once; result accumulates correctly.
	val := result(`
		function add[T](a: T, b: T) -> T { return a + b }
		function main() -> i64 {
			let x = add(1, 2)
			let y = add(x, 3)
			return add(y, 4)
		}
	`)
	testing.expect_value(t, val.(i64), i64(10))
}

@(test)
test_e2e_generic_struct_return_basic :: proc(t: ^testing.T) {
	// Generic function that returns a generic struct; field access on the result.
	val := result(`
		struct Stack[T] { top: T, size: int }
		function make_stack[T](val: T) -> Stack[T] {
			return Stack[T]{top = val, size = 1}
		}
		function main() -> i64 {
			let s = make_stack(99)
			return s.top
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

@(test)
test_e2e_generic_struct_return_size :: proc(t: ^testing.T) {
	// The non-type-param field (size: int) is also readable.
	val := result(`
		struct Stack[T] { top: T, size: int }
		function make_stack[T](val: T) -> Stack[T] {
			return Stack[T]{top = val, size = 3}
		}
		function main() -> i64 {
			let s = make_stack(0)
			return s.size
		}
	`)
	testing.expect_value(t, val.(i64), i64(3))
}

@(test)
test_e2e_generic_struct_return_then_pass :: proc(t: ^testing.T) {
	// Generic struct returned from one function and passed to another.
	val := result(`
		struct Stack[T] { top: T, size: int }
		function make_stack[T](val: T) -> Stack[T] {
			return Stack[T]{top = val, size = 1}
		}
		function peek[T](s: Stack[T]) -> T {
			return s.top
		}
		function main() -> i64 {
			let s = make_stack(55)
			return peek(s)
		}
	`)
	testing.expect_value(t, val.(i64), i64(55))
}

@(test)
test_e2e_generic_struct_return_two_type_params :: proc(t: ^testing.T) {
	// Generic function returning a two-parameter generic struct.
	val := result(`
		struct Pair[A, B] { first: A, second: B }
		function make_pair[A, B](a: A, b: B) -> Pair[A, B] {
			return Pair[A, B]{first = a, second = b}
		}
		function main() -> i64 {
			let p = make_pair(7, 3.14)
			return p.first
		}
	`)
	testing.expect_value(t, val.(i64), i64(7))
}

@(test)
test_e2e_generic_struct_return_get_first :: proc(t: ^testing.T) {
	// Generic function that takes and returns from a two-type-param struct.
	val := result(`
		struct Pair[A, B] { first: A, second: B }
		function make_pair[A, B](a: A, b: B) -> Pair[A, B] {
			return Pair[A, B]{first = a, second = b}
		}
		function get_first[A, B](p: Pair[A, B]) -> A {
			return p.first
		}
		function main() -> i64 {
			let p = make_pair(42, 1.0)
			return get_first(p)
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@test
test_e2e_nested_generic_struct_field_access :: proc(t: ^testing.T) {
	// Box[Box[int]] — two levels of nesting, field access traverses both.
	val := result(`
		struct Box[T] { value: T }
		function main() -> i64 {
			let inner = Box[int]{value = 99}
			let outer = Box[Box[int]]{value = inner}
			return outer.value.value
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

@test
test_e2e_nested_generic_struct_triple :: proc(t: ^testing.T) {
	// Box[Box[Box[int]]] — three levels of nesting.
	val := result(`
		struct Box[T] { value: T }
		function main() -> i64 {
			let a = Box[int]{value = 7}
			let b = Box[Box[int]]{value = a}
			let c = Box[Box[Box[int]]]{value = b}
			return c.value.value.value
		}
	`)
	testing.expect_value(t, val.(i64), i64(7))
}

@test
test_e2e_nested_generic_struct_unwrap :: proc(t: ^testing.T) {
	// Generic function unwrap[T](b: Box[T]) -> T called with Box[Box[int]] arg.
	val := result(`
		struct Box[T] { value: T }
		function unwrap[T](b: Box[T]) -> T {
			return b.value
		}
		function main() -> i64 {
			let inner = Box[int]{value = 42}
			let outer = Box[Box[int]]{value = inner}
			let mid = unwrap(outer)
			return mid.value
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@test
test_e2e_nested_generic_struct_wrap_return :: proc(t: ^testing.T) {
	// Generic function wrap[T](v: T) -> Box[T] called with Box[int] arg,
	// returning Box[Box[int]] — tests generic struct in return position.
	val := result(`
		struct Box[T] { value: T }
		function wrap[T](v: T) -> Box[T] {
			return Box[T]{value = v}
		}
		function main() -> i64 {
			let inner = Box[int]{value = 55}
			let outer = wrap(inner)
			return outer.value.value
		}
	`)
	testing.expect_value(t, val.(i64), i64(55))
}

@test
test_e2e_nested_generic_struct_pair_box :: proc(t: ^testing.T) {
	// Pair where one member is a generic struct Box[int].
	val := result(`
		struct Box[T] { value: T }
		struct Pair[A, B] { first: A, second: B }
		function main() -> i64 {
			let b = Box[int]{value = 13}
			let p = Pair[Box[int], int]{first = b, second = 99}
			return p.first.value
		}
	`)
	testing.expect_value(t, val.(i64), i64(13))
}

@test
test_e2e_addrof_basic :: proc(t: ^testing.T) {
	// &local gives a live pointer — field write through pointer is visible on original.
	val := result(`
		struct Point { x: int, y: int }
		function main() -> i64 {
			let p = Point{x = 10, y = 20}
			let ptr = &p
			ptr.x = 99
			return p.x
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

@test
test_e2e_addrof_passed_to_fn :: proc(t: ^testing.T) {
	// Pass &local to a function expecting ^T; mutation is visible after the call.
	val := result(`
		struct Counter { n: int }
		function inc(c: ^Counter) {
			c.n += 1
		}
		function main() -> i64 {
			let c = Counter{n = 0}
			inc(&c)
			inc(&c)
			inc(&c)
			return c.n
		}
	`)
	testing.expect_value(t, val.(i64), i64(3))
}

@test
test_e2e_addrof_two_aliases :: proc(t: ^testing.T) {
	// Two stack refs to the same local both see mutations.
	val := result(`
		struct Val { x: int }
		function main() -> i64 {
			let v = Val{x = 1}
			let a = &v
			let b = &v
			a.x = 42
			return b.x
		}
	`)
	testing.expect_value(t, val.(i64), i64(42))
}

@test
test_e2e_addrof_stored_in_let :: proc(t: ^testing.T) {
	// &local stored in a let, then used with auto-deref field access.
	val := result(`
		struct Point { x: int, y: int }
		function move(p: ^Point, dx: int, dy: int) {
			p.x += dx
			p.y += dy
		}
		function main() -> i64 {
			let pt = Point{x = 10, y = 20}
			let p = &pt
			move(p, 3, 4)
			return pt.x + pt.y
		}
	`)
	testing.expect_value(t, val.(i64), i64(37))
}

// ---- arrays ----

@test
test_e2e_array_literal_read :: proc(t: ^testing.T) {
	val := result(`
		function main() -> i64 {
			let a = Array[i64, 3]{10, 20, 30}
			return a[1]
		}
	`)
	testing.expect_value(t, val.(i64), i64(20))
}

@test
test_e2e_array_write_read :: proc(t: ^testing.T) {
	val := result(`
		function main() -> i64 {
			let a = Array[i64, 3]{1, 2, 3}
			a[0] = 99
			return a[0]
		}
	`)
	testing.expect_value(t, val.(i64), i64(99))
}

@test
test_e2e_array_sum_loop :: proc(t: ^testing.T) {
	val := result(`
		function main() -> i64 {
			let a = Array[i64, 5]{1, 2, 3, 4, 5}
			let sum = 0
			for let i = 0; i < 5; i += 1 {
				sum += a[i]
			}
			return sum
		}
	`)
	testing.expect_value(t, val.(i64), i64(15))
}

@test
test_e2e_array_last_element :: proc(t: ^testing.T) {
	val := result(`
		function main() -> i64 {
			let a = Array[i64, 4]{10, 20, 30, 40}
			return a[3]
		}
	`)
	testing.expect_value(t, val.(i64), i64(40))
}

@test
test_e2e_array_write_multiple :: proc(t: ^testing.T) {
	val := result(`
		function main() -> i64 {
			let a = Array[i64, 3]{0, 0, 0}
			a[0] = 5
			a[1] = 10
			a[2] = 15
			return a[0] + a[1] + a[2]
		}
	`)
	testing.expect_value(t, val.(i64), i64(30))
}
