// AI_GENERATED: GENERATED BY CLAUDE CODE
package vm

import "core:testing"
import "core:strings"
import bc "../../bytecode"
import "../../../lexer"

// ---- helpers ----

dummy_span :: proc() -> lexer.Span { return {} }

// build a function using the compiler and extract it
build_fn :: proc(name: string, build: proc(^bc.ByteCodeCompiler)) -> ^Function {
	comp := bc.new_bytecode_compiler(name, 0)
	build(&comp)
	return bc.compiler_end(&comp)
}

run :: proc(fn: ^Function) -> Maybe(VMError) {
	vm := new_vm()
	defer destroy_vm(&vm)
	return vm_interpret(&vm, fn)
}

run_top :: proc(fn: ^Function) -> Value {
	vm := new_vm()
	defer destroy_vm(&vm)
	vm_interpret(&vm, fn)
	if vm.stack_top == 0 do return Nil{}
	return vm.stack[vm.stack_top - 1]
}

// ---- vm_push / vm_pop / vm_peek ----

@(test)
test_push_pop :: proc(t: ^testing.T) {
	vm := new_vm()
	defer destroy_vm(&vm)
	vm_push(&vm, i64(42))
	val, err := vm_pop(&vm)
	testing.expect(t, err == nil)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_push_overflow :: proc(t: ^testing.T) {
	vm := new_vm()
	defer destroy_vm(&vm)
	for i in 0..<STACK_MAX {
		vm_push(&vm, i64(0))
	}
	err := vm_push(&vm, i64(0))
	testing.expect_value(t, err, Maybe(VMError)(.STACK_OVERFLOW))
}

@(test)
test_pop_underflow :: proc(t: ^testing.T) {
	vm := new_vm()
	defer destroy_vm(&vm)
	_, err := vm_pop(&vm)
	testing.expect_value(t, err, Maybe(VMError)(.STACK_UNDERFLOW))
}

@(test)
test_peek_does_not_consume :: proc(t: ^testing.T) {
	vm := new_vm()
	defer destroy_vm(&vm)
	vm_push(&vm, i64(99))
	vm_peek(&vm)
	testing.expect_value(t, vm.stack_top, u16(1))
}

// ---- is_falsy ----

@(test)
test_is_falsy :: proc(t: ^testing.T) {
	testing.expect(t,  is_falsy(false))
	testing.expect(t,  is_falsy(Nil{}))
	testing.expect(t, !is_falsy(true))
	testing.expect(t, !is_falsy(i64(0)))
	testing.expect(t, !is_falsy(i64(1)))
	testing.expect(t, !is_falsy("hello"))
}

// ---- arithmetic ----

@(test)
test_run_add_ints :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(1), span)
		bc.emit_constant(c, i64(2), span)
		bc.emit(c, .ADD, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	result := run_top(fn)
	testing.expect_value(t, result.(i64), i64(3))
}

@(test)
test_run_sub :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(10), span)
		bc.emit_constant(c, i64(3), span)
		bc.emit(c, .SUB, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(7))
}

@(test)
test_run_mul :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(4), span)
		bc.emit_constant(c, i64(5), span)
		bc.emit(c, .MUL, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(20))
}

@(test)
test_run_negate :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(5), span)
		bc.emit(c, .NEGATE, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(-5))
}

@(test)
test_run_type_error :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(1), span)
		bc.emit_constant(c, "hello", span)
		bc.emit(c, .ADD, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run(fn), Maybe(VMError)(.TYPE_ERROR))
}

// ---- division ----

@(test)
test_run_div :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(10), span)
		bc.emit_constant(c, i64(2), span)
		bc.emit(c, .DIV, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(5))
}

@(test)
test_run_division_by_zero :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(10), span)
		bc.emit_constant(c, i64(0), span)
		bc.emit(c, .DIV, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run(fn), Maybe(VMError)(.DIVISION_BY_ZERO))
}

// ---- comparison ----

@(test)
test_run_lt_true :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(1), span)
		bc.emit_constant(c, i64(2), span)
		bc.emit(c, .LT, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(bool), true)
}

@(test)
test_run_lt_false :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(5), span)
		bc.emit_constant(c, i64(2), span)
		bc.emit(c, .LT, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(bool), false)
}

@(test)
test_run_eq_true :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(42), span)
		bc.emit_constant(c, i64(42), span)
		bc.emit(c, .EQ, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(bool), true)
}

// ---- booleans ----

@(test)
test_run_true :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit(c, .TRUE, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(bool), true)
}

@(test)
test_run_not :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit(c, .TRUE, span)
		bc.emit(c, .NOT, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(bool), false)
}

// ---- nil ----

@(test)
test_run_nil :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit(c, .NIL, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	result := run_top(fn)
	_, ok := result.(Nil)
	testing.expect(t, ok, "expected Nil value")
}

// ---- globals ----

@(test)
test_run_define_get_global :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		// push value
		bc.emit_constant(c, i64(42), span)
		// add name to constant pool and emit DEFINE_GLOBAL + index
		name_idx, _ := bc.chunk_add_constant(bc.current_chunk(c), "x")
		bc.emit(c, .DEFINE_GLOBAL, span)
		bc.emit_byte(c, u8(name_idx), span)
		// GET_GLOBAL with same name index
		bc.emit(c, .GET_GLOBAL, span)
		bc.emit_byte(c, u8(name_idx), span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(42))
}

@(test)
test_run_undefined_global :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		name_idx, _ := bc.chunk_add_constant(bc.current_chunk(c), "missing")
		bc.emit(c, .GET_GLOBAL, span)
		bc.emit_byte(c, u8(name_idx), span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run(fn), Maybe(VMError)(.UNDEFINED_VARIABLE))
}

// ---- string pool unit tests ----

@(test)
test_pool_intern_returns_same_pointer :: proc(t: ^testing.T) {
	pool := string_pool_new()
	defer string_pool_destroy(&pool)
	a := string_pool_intern(&pool, "hello")
	b := string_pool_intern(&pool, "hello")
	testing.expect(t, raw_data(a) == raw_data(b), "same content must return same pointer")
}

@(test)
test_pool_intern_different_content :: proc(t: ^testing.T) {
	pool := string_pool_new()
	defer string_pool_destroy(&pool)
	a := string_pool_intern(&pool, "foo")
	b := string_pool_intern(&pool, "bar")
	testing.expect(t, raw_data(a) != raw_data(b), "different content must have different pointers")
}

@(test)
test_pool_intern_deduplicates :: proc(t: ^testing.T) {
	pool := string_pool_new()
	defer string_pool_destroy(&pool)
	string_pool_intern(&pool, "myr")
	string_pool_intern(&pool, "myr")
	string_pool_intern(&pool, "myr")
	testing.expect_value(t, len(pool.entries), 1)
}

@(test)
test_pool_intern_long_string_not_pooled :: proc(t: ^testing.T) {
	pool := string_pool_new()
	defer string_pool_destroy(&pool)
	// build a string longer than MAX_INTERN_LEN
	long := "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz"
	a := string_pool_intern(&pool, long)
	b := string_pool_intern(&pool, long)
	defer delete(a)
	defer delete(b)
	testing.expect(t, len(pool.entries) == 0, "long strings must not be added to pool")
	testing.expect(t, raw_data(a) != raw_data(b), "long strings get independent clones")
}

@(test)
test_pool_intern_empty_string :: proc(t: ^testing.T) {
	pool := string_pool_new()
	defer string_pool_destroy(&pool)
	a := string_pool_intern(&pool, "")
	b := string_pool_intern(&pool, "")
	testing.expect(t, raw_data(a) == raw_data(b))
	testing.expect_value(t, len(pool.entries), 1)
}

@(test)
test_pool_intern_independent_of_source :: proc(t: ^testing.T) {
	pool := string_pool_new()
	defer string_pool_destroy(&pool)
	// intern from two different source buffers with same content
	buf1 := "hello world"
	buf2 := "hello world"
	a := string_pool_intern(&pool, buf1)
	b := string_pool_intern(&pool, buf2)
	testing.expect(t, raw_data(a) == raw_data(b), "content equality must win over source pointer")
}

// ---- vm string interning integration ----

@(test)
test_vm_string_constant_interned :: proc(t: ^testing.T) {
	vm := new_vm()
	defer destroy_vm(&vm)
	// intern the same string twice through the pool directly
	s1 := string_pool_intern(&vm.strings, "hello")
	s2 := string_pool_intern(&vm.strings, "hello")
	testing.expect(t, raw_data(s1) == raw_data(s2))
}

@(test)
test_vm_string_eq_uses_pointer :: proc(t: ^testing.T) {
	// vm_values_equal for interned strings must be pointer equality
	vm := new_vm()
	defer destroy_vm(&vm)
	a := Value(string_pool_intern(&vm.strings, "myr"))
	b := Value(string_pool_intern(&vm.strings, "myr"))
	testing.expect(t, vm_values_equal(a, b))
}

@(test)
test_vm_string_neq_different :: proc(t: ^testing.T) {
	vm := new_vm()
	defer destroy_vm(&vm)
	a := Value(string_pool_intern(&vm.strings, "foo"))
	b := Value(string_pool_intern(&vm.strings, "bar"))
	testing.expect(t, !vm_values_equal(a, b))
}

@(test)
test_vm_concat_result_interned :: proc(t: ^testing.T) {
	pool := string_pool_new()
	defer string_pool_destroy(&pool)
	tmp  := strings.concatenate({"hel", "lo"})
	s    := string_pool_intern(&pool, tmp)
	s2   := string_pool_intern(&pool, "hello")
	if raw_data(tmp) != raw_data(s) { delete(tmp) }
	testing.expect(t, raw_data(s) == raw_data(s2), "concat result and literal must share pointer")
}

// ---- pop ----

@(test)
test_run_pop :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(1), span)
		bc.emit_constant(c, i64(2), span)
		bc.emit(c, .POP, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	// after POP, only the first constant (1) remains
	testing.expect_value(t, run_top(fn).(i64), i64(1))
}

// ---- NEW / HEAP_GET / HEAP_SET / HEAP_LOAD ----

@(test)
test_new_pushes_ptr :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(10), span)
		bc.emit_constant(c, i64(20), span)
		bc.emit(c, .NEW, span)
		bc.emit_byte(c, 2, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	val := run_top(fn)
	_, ok := val.([^]Value)
	testing.expect(t, ok, "NEW must push a [^]Value onto the stack")
}

@(test)
test_heap_get_offset_0 :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(10), span)
		bc.emit_constant(c, i64(20), span)
		bc.emit(c, .NEW, span)
		bc.emit_byte(c, 2, span)
		bc.emit(c, .HEAP_GET, span)
		bc.emit_byte(c, 0, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(10))
}

@(test)
test_heap_get_offset_1 :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(10), span)
		bc.emit_constant(c, i64(20), span)
		bc.emit(c, .NEW, span)
		bc.emit_byte(c, 2, span)
		bc.emit(c, .HEAP_GET, span)
		bc.emit_byte(c, 1, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(20))
}

@(test)
test_heap_load_top_slot :: proc(t: ^testing.T) {
	// HEAP_LOAD 2: pops ptr, pushes slots[0], slots[1]; top is slots[1]
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(10), span)
		bc.emit_constant(c, i64(20), span)
		bc.emit(c, .NEW, span)
		bc.emit_byte(c, 2, span)
		bc.emit(c, .HEAP_LOAD, span)
		bc.emit_byte(c, 2, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(20))
}

@(test)
test_heap_load_first_slot :: proc(t: ^testing.T) {
	// POP the top after HEAP_LOAD to expose slots[0]
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(10), span)
		bc.emit_constant(c, i64(20), span)
		bc.emit(c, .NEW, span)
		bc.emit_byte(c, 2, span)
		bc.emit(c, .HEAP_LOAD, span)
		bc.emit_byte(c, 2, span)
		bc.emit(c, .POP, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(10))
}

@(test)
test_heap_set_write :: proc(t: ^testing.T) {
	// push 99, NEW 1{42}, HEAP_SET 0 → ptr[0]=99; HEAP_GET 0 → 99
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		// allocate: slot[0] = 42
		bc.emit_constant(c, i64(42), span)
		bc.emit(c, .NEW, span)
		bc.emit_byte(c, 1, span)
		// ptr is at stack[0]; store ptr in local 0
		bc.emit(c, .SET_LOCAL, span)
		bc.emit_byte(c, 0, span)
		// push new value, then ptr, then HEAP_SET
		bc.emit_constant(c, i64(99), span)
		bc.emit(c, .GET_LOCAL, span)
		bc.emit_byte(c, 0, span)
		bc.emit(c, .HEAP_SET, span)
		bc.emit_byte(c, 0, span)
		// POP the leftover value (99)
		bc.emit(c, .POP, span)
		// GET_LOCAL ptr, HEAP_GET 0 → should be 99 now
		bc.emit(c, .GET_LOCAL, span)
		bc.emit_byte(c, 0, span)
		bc.emit(c, .HEAP_GET, span)
		bc.emit_byte(c, 0, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(99))
}

@(test)
test_heap_set_leaves_value_on_stack :: proc(t: ^testing.T) {
	// HEAP_SET must leave the value on the stack (like SET_LOCAL)
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(42), span)
		bc.emit(c, .NEW, span)
		bc.emit_byte(c, 1, span)
		bc.emit(c, .SET_LOCAL, span)
		bc.emit_byte(c, 0, span)
		bc.emit_constant(c, i64(77), span)  // value to set
		bc.emit(c, .GET_LOCAL, span)
		bc.emit_byte(c, 0, span)            // ptr
		bc.emit(c, .HEAP_SET, span)
		bc.emit_byte(c, 0, span)
		// after HEAP_SET the value (77) is still on stack
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(77))
}

@(test)
test_heap_get_null_deref :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		nil_ptr: [^]bc.Value = nil
		bc.emit_constant(c, nil_ptr, span)
		bc.emit(c, .HEAP_GET, span)
		bc.emit_byte(c, 0, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run(fn), Maybe(VMError)(.NULL_DEREF))
}

@(test)
test_heap_set_null_deref :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(1), span)
		nil_ptr: [^]bc.Value = nil
		bc.emit_constant(c, nil_ptr, span)
		bc.emit(c, .HEAP_SET, span)
		bc.emit_byte(c, 0, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run(fn), Maybe(VMError)(.NULL_DEREF))
}

@(test)
test_heap_load_null_deref :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		nil_ptr: [^]bc.Value = nil
		bc.emit_constant(c, nil_ptr, span)
		bc.emit(c, .HEAP_LOAD, span)
		bc.emit_byte(c, 2, span)
		bc.emit(c, .RETURN, span)
		bc.emit_byte(c, 1, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run(fn), Maybe(VMError)(.NULL_DEREF))
}
