// AI_GENERATED: GENERATED BY CLAUDE CODE
package vm

import "core:testing"
import bc "../../bytecode"
import "../../../lexer"

// ---- helpers ----

dummy_span :: proc() -> lexer.Span { return {} }

// build a function using the compiler and extract it
build_fn :: proc(name: string, build: proc(^bc.ByteCodeCompiler)) -> ^Function {
	comp := bc.new_bytecode_compiler(name, 0)
	build(&comp)
	return bc.compiler_end(&comp)
}

run :: proc(fn: ^Function) -> Maybe(VMError) {
	vm := new_vm()
	defer destroy_vm(&vm)
	return vm_interpret(&vm, fn)
}

run_top :: proc(fn: ^Function) -> Value {
	vm := new_vm()
	defer destroy_vm(&vm)
	vm_interpret(&vm, fn)
	if vm.stack_top == 0 do return Nil{}
	return vm.stack[vm.stack_top - 1]
}

// ---- vm_push / vm_pop / vm_peek ----

@(test)
test_push_pop :: proc(t: ^testing.T) {
	vm := new_vm()
	defer destroy_vm(&vm)
	vm_push(&vm, i64(42))
	val, err := vm_pop(&vm)
	testing.expect(t, err == nil)
	testing.expect_value(t, val.(i64), i64(42))
}

@(test)
test_push_overflow :: proc(t: ^testing.T) {
	vm := new_vm()
	defer destroy_vm(&vm)
	for i in 0..<STACK_MAX {
		vm_push(&vm, i64(0))
	}
	err := vm_push(&vm, i64(0))
	testing.expect_value(t, err, Maybe(VMError)(.STACK_OVERFLOW))
}

@(test)
test_pop_underflow :: proc(t: ^testing.T) {
	vm := new_vm()
	defer destroy_vm(&vm)
	_, err := vm_pop(&vm)
	testing.expect_value(t, err, Maybe(VMError)(.STACK_UNDERFLOW))
}

@(test)
test_peek_does_not_consume :: proc(t: ^testing.T) {
	vm := new_vm()
	defer destroy_vm(&vm)
	vm_push(&vm, i64(99))
	vm_peek(&vm)
	testing.expect_value(t, vm.stack_top, u16(1))
}

// ---- is_falsy ----

@(test)
test_is_falsy :: proc(t: ^testing.T) {
	testing.expect(t,  is_falsy(false))
	testing.expect(t,  is_falsy(Nil{}))
	testing.expect(t, !is_falsy(true))
	testing.expect(t, !is_falsy(i64(0)))
	testing.expect(t, !is_falsy(i64(1)))
	testing.expect(t, !is_falsy("hello"))
}

// ---- arithmetic ----

@(test)
test_run_add_ints :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(1), span)
		bc.emit_constant(c, i64(2), span)
		bc.emit(c, .ADD, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	result := run_top(fn)
	testing.expect_value(t, result.(i64), i64(3))
}

@(test)
test_run_sub :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(10), span)
		bc.emit_constant(c, i64(3), span)
		bc.emit(c, .SUB, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(7))
}

@(test)
test_run_mul :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(4), span)
		bc.emit_constant(c, i64(5), span)
		bc.emit(c, .MUL, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(20))
}

@(test)
test_run_negate :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(5), span)
		bc.emit(c, .NEGATE, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(-5))
}

@(test)
test_run_type_error :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(1), span)
		bc.emit_constant(c, "hello", span)
		bc.emit(c, .ADD, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run(fn), Maybe(VMError)(.TYPE_ERROR))
}

// ---- division ----

@(test)
test_run_div :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(10), span)
		bc.emit_constant(c, i64(2), span)
		bc.emit(c, .DIV, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(5))
}

@(test)
test_run_division_by_zero :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(10), span)
		bc.emit_constant(c, i64(0), span)
		bc.emit(c, .DIV, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run(fn), Maybe(VMError)(.DIVISION_BY_ZERO))
}

// ---- comparison ----

@(test)
test_run_lt_true :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(1), span)
		bc.emit_constant(c, i64(2), span)
		bc.emit(c, .LT, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(bool), true)
}

@(test)
test_run_lt_false :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(5), span)
		bc.emit_constant(c, i64(2), span)
		bc.emit(c, .LT, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(bool), false)
}

@(test)
test_run_eq_true :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(42), span)
		bc.emit_constant(c, i64(42), span)
		bc.emit(c, .EQ, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(bool), true)
}

// ---- booleans ----

@(test)
test_run_true :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit(c, .TRUE, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(bool), true)
}

@(test)
test_run_not :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit(c, .TRUE, span)
		bc.emit(c, .NOT, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(bool), false)
}

// ---- nil ----

@(test)
test_run_nil :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit(c, .NIL, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	result := run_top(fn)
	_, ok := result.(Nil)
	testing.expect(t, ok, "expected Nil value")
}

// ---- globals ----

@(test)
test_run_define_get_global :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		// push value
		bc.emit_constant(c, i64(42), span)
		// add name to constant pool and emit DEFINE_GLOBAL + index
		name_idx, _ := bc.chunk_add_constant(bc.current_chunk(c), "x")
		bc.emit(c, .DEFINE_GLOBAL, span)
		bc.emit_byte(c, u8(name_idx), span)
		// GET_GLOBAL with same name index
		bc.emit(c, .GET_GLOBAL, span)
		bc.emit_byte(c, u8(name_idx), span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run_top(fn).(i64), i64(42))
}

@(test)
test_run_undefined_global :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		name_idx, _ := bc.chunk_add_constant(bc.current_chunk(c), "missing")
		bc.emit(c, .GET_GLOBAL, span)
		bc.emit_byte(c, u8(name_idx), span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	testing.expect_value(t, run(fn), Maybe(VMError)(.UNDEFINED_VARIABLE))
}

// ---- pop ----

@(test)
test_run_pop :: proc(t: ^testing.T) {
	fn := build_fn("test", proc(c: ^bc.ByteCodeCompiler) {
		span := dummy_span()
		bc.emit_constant(c, i64(1), span)
		bc.emit_constant(c, i64(2), span)
		bc.emit(c, .POP, span)
		bc.emit(c, .RETURN, span)
	})
	defer bc.function_free(fn)
	// after POP, only the first constant (1) remains
	testing.expect_value(t, run_top(fn).(i64), i64(1))
}
