// AI_GENERATED: GENERATED BY CLAUDE CODE
package typechecker

import "core:testing"
import "../../parser"
import nr "../nameresolution"

// ---- helpers ----

TcSetup :: struct {
	result: TypecheckResult,
	nrr:    nr.NRResult,
}

tc_run :: proc(src: string) -> (setup: TcSetup, ok: bool) {
	p := parser.new_parser(src)
	ast := parser.parse_program(&p)
	setup.nrr = nr.resolve_program(&ast)
	if setup.nrr.error_count > 0 {
		nr.nr_result_destroy(&setup.nrr)
		return {}, false
	}
	setup.result = typecheck(&ast, &setup.nrr)
	ok = true
	return
}

tc_destroy :: proc(s: ^TcSetup) {
	tc_result_destroy(&s.result)
	nr.nr_result_destroy(&s.nrr)
}

// ---- clean programs: must produce zero errors ----

@(test)
test_void_function_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() { }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_int_arithmetic_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function add(x: i64, y: i64) -> i64 { x + y }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_bool_negation_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function check(b: bool) -> bool { !b }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_let_with_annotation_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() { let x: i64 = 5 }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_let_chain_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() { let x = 5 let y = x + 1 }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_if_bool_condition_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() { if true { } }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_forward_call_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`
function main() { foo() }
function foo() { }
`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_explicit_return_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function id(x: i64) -> i64 { return x }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_tail_expr_return_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function answer() -> i64 { 42 }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_call_correct_args_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`
function id(x: i64) -> i64 { x }
function main() { id(5) }
`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_comparison_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function cmp(x: i64, y: i64) -> bool { x < y }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_logical_and_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function both(a: bool, b: bool) -> bool { a && b }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_for_loop_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() { for let i = 0; i < 10; i + 0 { } }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

// ---- error programs: must produce at least one error ----

// test_wrong_return_type_via_tail_expression is intentionally absent: the parser
// always wraps body expressions in ExpressionStatement — BlockExpression.result is
// never set — so tail-expression return-type checking is a no-op until the parser
// distinguishes tail expressions from regular statements.

@(test)
test_bool_in_arithmetic_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function add(x: i64) -> i64 { x + true }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect(t, s.result.error_count > 0, "expected type error: bool used in arithmetic")
}

@(test)
test_let_annotation_mismatch_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() { let x: bool = 5 }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect(t, s.result.error_count > 0, "expected type error: int literal assigned to bool binding")
}

@(test)
test_if_int_condition_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() { if 5 { } }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect(t, s.result.error_count > 0, "expected type error: int used as if condition")
}

@(test)
test_call_wrong_arg_type_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`
function id(x: i64) -> i64 { x }
function main() { id(true) }
`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect(t, s.result.error_count > 0, "expected type error: bool passed where i64 expected")
}

@(test)
test_call_wrong_arg_count_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`
function add(x: i64, y: i64) -> i64 { x + y }
function main() { add(1) }
`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect(t, s.result.error_count > 0, "expected error: wrong argument count")
}

@(test)
test_explicit_return_wrong_type_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() -> i64 { return true }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect(t, s.result.error_count > 0, "expected type error: bool returned from i64 function via return stmt")
}

// ---- type assertion tests: verify specific node types ----
//
// Node layout for `function main() { let x = <expr> }` with no type annotations:
//   nodes[0] = LiteralExpression (the value)
//   nodes[1] = LetStatement
//   nodes[2] = FunctionDecl
//
// This layout holds as long as the body contains exactly one unannotated let with a literal value.

@(test)
test_int_literal_inferred :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() { let x = 5 }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	if len(s.result.types) < 2 do return
	testing.expect_value(t, s.result.types[0], INT_TYPE)  // literal 5
	testing.expect_value(t, s.result.types[1], INT_TYPE)  // let x
}

@(test)
test_bool_literal_inferred :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() { let x = true }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	if len(s.result.types) < 2 do return
	testing.expect_value(t, s.result.types[0], BOOL_TYPE)  // literal true
	testing.expect_value(t, s.result.types[1], BOOL_TYPE)  // let x
}

@(test)
test_float_literal_inferred :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() { let x = 3.14 }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	if len(s.result.types) < 2 do return
	testing.expect_value(t, s.result.types[0], FLOAT_TYPE)  // literal 3.14
	testing.expect_value(t, s.result.types[1], FLOAT_TYPE)  // let x
}

@(test)
test_fn_type_in_table :: proc(t: ^testing.T) {
	s, ok := tc_run(`function main() { }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)

	found := false
	for info in s.result.type_table {
		if _, is_fn := info.(FnType); is_fn {
			found = true
			break
		}
	}
	testing.expect(t, found, "expected at least one FnType in the type table")
}

@(test)
test_fn_with_params_type_registered :: proc(t: ^testing.T) {
	// add has params [i64, i64] and return type i64
	s, ok := tc_run(`function add(x: i64, y: i64) -> i64 { x + y }`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)

	found := false
	for info in s.result.type_table {
		fn, is_fn := info.(FnType)
		if !is_fn do continue
		if len(fn.params) == 2 && fn.params[0] == INT_TYPE && fn.params[1] == INT_TYPE && fn.return_type == INT_TYPE {
			found = true
			break
		}
	}
	testing.expect(t, found, "expected FnType(i64,i64)->i64 in the type table")
}

// ---- structs ----

@(test)
test_struct_decl_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`
		struct Point { x: float, y: float }
		function main() { }
	`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_struct_literal_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = 1.0, y = 2.0} }
	`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_struct_field_access_no_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = 1.0, y = 2.0} let n = p.x }
	`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_struct_field_wrong_type_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = true, y = 2.0} }
	`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect(t, s.result.error_count > 0, "expected type error for bool in float field")
}

@(test)
test_struct_unknown_field_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = 1.0, z = 2.0} }
	`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect(t, s.result.error_count > 0, "expected error for unknown field 'z'")
}

@(test)
test_struct_field_access_type_inferred :: proc(t: ^testing.T) {
	s, ok := tc_run(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = 1.0, y = 2.0} let n: float = p.x }
	`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect_value(t, s.result.error_count, u16(0))
}

@(test)
test_struct_field_access_wrong_type_errors :: proc(t: ^testing.T) {
	s, ok := tc_run(`
		struct Point { x: float, y: float }
		function main() { let p = Point{x = 1.0, y = 2.0} let n: int = p.x }
	`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	testing.expect(t, s.result.error_count > 0, "expected type error: float assigned to int")
}

@(test)
test_struct_registered_in_type_table :: proc(t: ^testing.T) {
	s, ok := tc_run(`
		struct Point { x: float, y: float }
		function main() { }
	`)
	if !ok { testing.fail(t); return }
	defer tc_destroy(&s)
	found := false
	for info in s.result.type_table {
		if st, is_st := info.(StructType); is_st && st.name == "Point" {
			found = true
			break
		}
	}
	testing.expect(t, found, "expected StructType 'Point' in type table")
}
